In [98]:
import geopandas as gpd
from requests import Request
from owslib.wfs import WebFeatureService

In [99]:
url = "https://pubgeo.zwemwater.nl/geoserver/zwr_public/wfs"
wfs = WebFeatureService(url=url)

In [100]:
def load_wfs_layer(layer_name):
    params = dict(service='WFS', version="2.0.0", request='GetFeature',
      typeName=layer_name, outputFormat='json', srsName="EPSG:4326")
    wfs_request_url = Request('GET', url, params=params).prepare().url
    return gpd.read_file(wfs_request_url)

# Data

### Zwemplekken

In [101]:
zwemplekken = load_wfs_layer("zwr_public:zwemplekken")
zwemplekken = zwemplekken.drop(columns=['id', 'datum']).set_index('key_id')
zwemplekken

,korte_naam,naam,status,zwemwaterlocatie_id,geometry
key_id,,,,,
6187300,Voorveldse Polder,Voorveldse Polder,NEGATIEF_ZWEMADVIES,1185,POINT (5.15220 52.10050)
2316,'t Kleine Zeetje,Recreatiepark 't Kleine Zeetje,NEGATIEF_ZWEMADVIES,1595,POINT (5.37620 52.26020)
1954,Plas Vrijenburgbos,Plas Vrijenburgbos,NEGATIEF_ZWEMADVIES,1233,POINT (4.50030 51.86800)
1962,Kralinger Esch,Kralinger Esch,NEGATIEF_ZWEMADVIES,1241,POINT (4.52530 51.91380)
2307,De Oude Pol,De Oude Pol,NEGATIEF_ZWEMADVIES,1586,POINT (5.72590 52.39250)
...,...,...,...,...,...
8184932,'t Gorsselaar,Bussloo 't Gorsselaar,goed,8184902,POINT (6.09630 52.20210)
8184934,De Kuiter,Bussloo De Kuiter (Naturistenstrand),goed,8184903,POINT (6.09980 52.19590)
8186500,Aquapark,Kempervennen Aquapark,goed,8186460,POINT (5.42470 51.32720)
8192100,Oude Tol,Oude Tol,goed,8192060,POINT (4.39750 51.83050)
8194230,Badstrand Ballum,"Badstrand Ballum, Ameland",goed,8194200,POINT (5.69590 53.46420)

In [102]:
zwemplekken_details = load_wfs_layer("zwr_public:zwemplekken_details")
zwemplekken_details = zwemplekken_details.drop(columns=["id", "info_id", "geometry", "datum"])
zwemplekken_details

,adr_huisletter,adr_huisnummer,adr_huisnummertoevoeging,adr_postcode,adr_straat,adr_woonplaats,info_filename,info_length,info_mime_type,key_id,...,org_straat,org_telefoon,org_website,org_woonplaats,status,taal,tekst,toegang,website,zwemwaterlocatie_id
0,None,NaN,None,None,De Dreef,Heerenveen,FR-043-001 De Heide.jpg,356023.0,image/jpeg,1676,...,,0513-617 617,http://www.heerenveen.nl,Heerenveen,goed,nl,"Het recreatiegebied “De Heide”, ligt aan de zu...",OPENBAAR ONBETAALD,None,955
1,,NaN,,None,Spokedam,Noordwolde,FR-046-001 Spoekeplas.jpg,297473.0,image/pjpeg,1677,...,,050 707 4444,http://www.staatsbosbeheer.nl,Groningen,goed,nl,Het zwemwater Spoekeplas ligt ten zuidwesten v...,OPENBAAR ONBETAALD,None,956
2,None,NaN,None,None,Canada,Appelscha,Canadameer Appelscha.png,212248.0,image/png,1678,...,,050 707 4444,http://www.staatsbosbeheer.nl,Groningen,goed,nl,Het Canadameer (ook wel Aekingermeer genoemd) ...,OPENBAAR ONBETAALD,None,957
3,None,NaN,None,None,Kleasterkampen,Smalle Ee,FR-028-001 Smeliester SaÌ‚n.jpg,210638.0,image/pjpeg,1680,...,,0512-581234,http://www.smallingerland.nl,Drachten,goed,nl,Het zwemwater ligt aan de zuidzijde van het ge...,OPENBAAR ONBETAALD,None,959
4,None,NaN,None,None,Bildreed,Rottevalle,FR-027-001 De Leien.jpg,209646.0,image/pjpeg,1681,...,,050 707 4444,http://www.staatsbosbeheer.nl,Groningen,goed,nl,Het zwemwater ligt enkele kilometers ten noord...,OPENBAAR ONBETAALD,None,960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
950,None,NaN,None,None,Kneuterstraat,Wilp,GLD-004-007 BUSSLOO GORSSELAAR 2020.jpg,2995096.0,image/jpeg,8184932,...,Westervoortsedijk 73-LB,026-3848800,http://www.leisurelands.nl,Arnhem,goed,nl,De recreatieplas Bussloo ligt temidden van de ...,Openbaar betaald parkeren voor auto's,http://www.leisurelands.nl/,8184902
951,None,NaN,None,None,Bloemenksweg,Wilp,GLD-004-013 BUSSLOO DE KUITER 2020.jpg,2981855.0,image/jpeg,8184934,...,Westervoortsedijk 73-LB,026-3848800,http://www.leisurelands.nl,Arnhem,goed,nl,De recreatieplas Bussloo ligt temidden van de ...,"Openbaar, betaald parkeren voor auto's",http://www.leisurelands.nl/,8184903
952,None,8.0,None,5563VB,Kempervennendreef,Westerhoven,None,NaN,None,8186500,...,Bosscheweg,(0411) 618 618,http://www.dommel.nl/,Boxtel,goed,nl,zwemlocatie Aquapark is ingericht als een drij...,Openbaar toegankelijk via kaartjesverkoop,None,8186460
953,None,35.0,None,3263RA,Randweg,Oud-Beijerland,None,NaN,None,8192100,...,Sportlaan,088-6473647,https://www.gemeentehw.nl/,Maasdam,goed,nl,De zwemlocatie heeft een zwembaai gelegen aan ...,None,None,8192060
954,None,NaN,None,None,None,Ballum,None,NaN,None,8194230,...,None,0519-555555,http://www.ameland.nl,Ameland,goed,nl,Zwemlocatie Badstrand Ballum is een zwemlocati...,None,None,8194200

In [103]:
zwemplekken_details.columns

Index(['adr_huisletter', 'adr_huisnummer', 'adr_huisnummertoevoeging',
       'adr_postcode', 'adr_straat', 'adr_woonplaats', 'info_filename',
       'info_length', 'info_mime_type', 'key_id', 'korte_naam', 'naam',
       'objecttype', 'org_bedrijfsnaam', 'org_email', 'org_fax',
       'org_huisletter', 'org_huisnumeer', 'org_huisnummertoevoeging',
       'org_id', 'org_postcode', 'org_straat', 'org_telefoon', 'org_website',
       'org_woonplaats', 'status', 'taal', 'tekst', 'toegang', 'website',
       'zwemwaterlocatie_id'],
      dtype='object')

In [104]:
photos = load_wfs_layer("zwr_public:locatiefotos")
photos

,id,filename,key_id,length,mime_type,zwemplek_id,geometry
0,locatiefotos.fid-54ccab89_1913661bc04_-13d7,testgegevens.csv,559072,23483,application/vnd.ms-excel,NaN,None
1,locatiefotos.fid-54ccab89_1913661bc04_-13d6,18-07-2012.jpg,559074,18482,image/pjpeg,1762.0,"POLYGON ((5.99780 52.31100, 5.99800 52.31090, ..."
2,locatiefotos.fid-54ccab89_1913661bc04_-13d5,FR-005-001 Badstrand Nes.jpg,1092,327074,image/pjpeg,NaN,None
3,locatiefotos.fid-54ccab89_1913661bc04_-13d4,FR-004-001 Badstrand Hollum.jpg,1091,280508,image/pjpeg,NaN,None
4,locatiefotos.fid-54ccab89_1913661bc04_-13d3,FR-009-001 De Vleyen.jpg,1093,271129,image/pjpeg,NaN,None
...,...,...,...,...,...,...,...
5825,locatiefotos.fid-54ccab89_1913661bc04_2ea,06-08-2024 CNINAC10.pdf,8343751,97704,application/pdf,NaN,None
5826,locatiefotos.fid-54ccab89_1913661bc04_2eb,waarschuwing i.v.m. blauwalg .docx,8343752,12918,application/vnd.openxmlformats-officedocument....,NaN,None
5827,locatiefotos.fid-54ccab89_1913661bc04_2ec,waarschuwing i.v.m. blauwalg .docx,8343753,12918,application/vnd.openxmlformats-officedocument....,NaN,None
5828,locatiefotos.fid-54ccab89_1913661bc04_2ed,waarschuwing i.v.m. blauwalg .docx,8343754,12918,application/vnd.openxmlformats-officedocument....,NaN,None
5829,locatiefotos.fid-54ccab89_1913661bc04_2ee,waarschuwing i.v.m. blauwalg .docx,8343755,12918,application/vnd.openxmlformats-officedocument....,NaN,None

In [105]:
photos["mime_type"].unique()

array(['application/vnd.ms-excel', 'image/pjpeg', 'image/jpeg',
       'image/png', 'application/pdf', 'application/vnd.adobe.pdx',
       'application/octet-stream',
       'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
       'application/msword',
       'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
       'text/plain', 'ds/document', 'text/html'], dtype=object)

In [106]:
photos = photos[
    photos['mime_type'].isin([
        'image/pjpeg', 
        'image/jpeg',
        'image/png'
    ])
]
photos

,id,filename,key_id,length,mime_type,zwemplek_id,geometry
1,locatiefotos.fid-54ccab89_1913661bc04_-13d6,18-07-2012.jpg,559074,18482,image/pjpeg,1762.0,"POLYGON ((5.99780 52.31100, 5.99800 52.31090, ..."
2,locatiefotos.fid-54ccab89_1913661bc04_-13d5,FR-005-001 Badstrand Nes.jpg,1092,327074,image/pjpeg,NaN,None
3,locatiefotos.fid-54ccab89_1913661bc04_-13d4,FR-004-001 Badstrand Hollum.jpg,1091,280508,image/pjpeg,NaN,None
4,locatiefotos.fid-54ccab89_1913661bc04_-13d3,FR-009-001 De Vleyen.jpg,1093,271129,image/pjpeg,NaN,None
5,locatiefotos.fid-54ccab89_1913661bc04_-13d2,FR-006-001 Badstrand Buren.jpg,1094,299640,image/pjpeg,NaN,None
...,...,...,...,...,...,...,...
5735,locatiefotos.fid-54ccab89_1913661bc04_290,IMG_1050.JPG,8282812,5113412,image/jpeg,NaN,None
5794,locatiefotos.fid-54ccab89_1913661bc04_2cb,20240718_123847.jpg,8314630,8184607,image/jpeg,NaN,None
5795,locatiefotos.fid-54ccab89_1913661bc04_2cc,20240718_123847.jpg,8314631,8184607,image/jpeg,NaN,None
5796,locatiefotos.fid-54ccab89_1913661bc04_2cd,20240718_132622.jpg,8314632,8902420,image/jpeg,NaN,None
5821,locatiefotos.fid-54ccab89_1913661bc04_2e6,IMG-20240803-WA0000.jpg,8334760,345646,image/jpeg,NaN,None

In [107]:
photos = photos.query("zwemplek_id.notnull()")
photodata = photos[['zwemplek_id', 'key_id', 'filename']].copy()
photodata['zwemplek_id'] = photodata['zwemplek_id'].astype(int)
photodata['key_id'] = "https://register.zwemwater.nl/zwr/api/files/" + photodata['key_id'].astype(str)
for item in photodata.query('zwemplek_id == 6187300').iterrows():
    print(item)

zwemplek_id
key_id
filename

In [108]:
base_data = zwemplekken_details.copy()
base_data = base_data[["zwemwaterlocatie_id", "naam", "korte_naam", "status", "tekst", "info_filename", "website"]]
base_data

,zwemwaterlocatie_id,naam,korte_naam,status,tekst,info_filename,website
0,955,De Heide,Heide,goed,"Het recreatiegebied “De Heide”, ligt aan de zu...",FR-043-001 De Heide.jpg,None
1,956,Spoekeplas,Spoekeplas,goed,Het zwemwater Spoekeplas ligt ten zuidwesten v...,FR-046-001 Spoekeplas.jpg,None
2,957,Canadameer,Canadameer,goed,Het Canadameer (ook wel Aekingermeer genoemd) ...,Canadameer Appelscha.png,None
3,959,Smeliester Sân,Smeliester Sân,goed,Het zwemwater ligt aan de zuidzijde van het ge...,FR-028-001 Smeliester SaÌ‚n.jpg,None
4,960,De Leien,De Leien,goed,Het zwemwater ligt enkele kilometers ten noord...,FR-027-001 De Leien.jpg,None
...,...,...,...,...,...,...,...
950,8184902,Bussloo 't Gorsselaar,'t Gorsselaar,goed,De recreatieplas Bussloo ligt temidden van de ...,GLD-004-007 BUSSLOO GORSSELAAR 2020.jpg,http://www.leisurelands.nl/
951,8184903,Bussloo De Kuiter (Naturistenstrand),De Kuiter,goed,De recreatieplas Bussloo ligt temidden van de ...,GLD-004-013 BUSSLOO DE KUITER 2020.jpg,http://www.leisurelands.nl/
952,8186460,Kempervennen Aquapark,Aquapark,goed,zwemlocatie Aquapark is ingericht als een drij...,None,None
953,8192060,Oude Tol,Oude Tol,goed,De zwemlocatie heeft een zwembaai gelegen aan ...,None,None
954,8194200,"Badstrand Ballum, Ameland",Badstrand Ballum,goed,Zwemlocatie Badstrand Ballum is een zwemlocati...,None,None

In [109]:
zwemplekdata = zwemplekken.merge(base_data, left_on="zwemwaterlocatie_id", right_on="zwemwaterlocatie_id", how="left")
zwemplekdata['lat'] = zwemplekdata['geometry'].y
zwemplekdata['lon'] = zwemplekdata['geometry'].x
zwemplekdata = zwemplekdata.drop(columns=["korte_naam_x", "naam_x", "status_x", "geometry"])
zwemplekdata = zwemplekdata.rename(columns={
    "naam_y": "naam",
    "korte_naam_y": "korte_naam",
    "status_y": "status"
})
zwemplekdata.sort_values(by=["naam"], inplace=True)
zwemplekdata

,zwemwaterlocatie_id,naam,korte_naam,status,tekst,info_filename,website,lat,lon
1610,1323,Engelermeer Oost,Engelermeer Oost,goed,Het Engelermeer is een serie kunstmatige plass...,NB-031-001 Engelermeer Oost.jpg,None,51.7046,5.2461
1589,1259,'T Hoefsven,'T Hoefsven,goed,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,None,51.6761,5.0942
355,1341,'T Nije Hemelriek,'T Nije Hemelriek,goed,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,None,52.9725,6.7556
1618,1315,'T Schaartven,'T Schaartven,goed,"‘t Schaartven is een voormalige zandwinplas, g...",None,None,51.5735,5.9749
358,1344,'T Veenmeer,'T Veenmeer,goed,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,None,53.0829,6.6303
...,...,...,...,...,...,...,...,...,...
68,7941840,strand Kortgene Paardekreek,Paardekreek,WAARSCHUWING,Door camping de Paardekreek aangelegd zandstra...,None,None,51.5496,3.8096
1947,7356682,strand zoutkamp,None,goed,strand zoutkamp in onderzoek,None,None,53.3388,6.2973
1921,6837320,strand zuid Oldambtmeer,strand zuid,goed,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,None,53.1651,7.0372
1920,6997562,strandje Brouwershaven,Brouwershaven,goed,Strandje naast jachthaven van Brouwershaven,None,None,51.7315,3.9154
319,1240,t Zwarte Plasje,'t Zwarte Plasje,goed,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,None,51.9593,4.4913

### EU statussen

In [110]:
eu_designations = load_wfs_layer("zwr_public:eustatussen")
eu_designations = eu_designations[eu_designations['jaar'] == 2023].drop(columns=['type_eu_status_id', 'geometry', 'omschrijving', 'id'])
eu_designations

     code   key_id  jaar  zwemwaterlocatie_id
7010    1  8135490  2023                 1267
7011    1  8135491  2023                 1268
7012    1  8135492  2023                 1270
7013    1  8135493  2023                 1271
7014    1  8135494  2023                 1273
...   ...      ...   ...                  ...
7751    4  8167548  2023                 1112
7752    4  8167553  2023                 1118
7753    3  8167559  2023                 1124
7754    4  8167555  2023                 1120
7755    4  8167550  2023                 1114

[731 rows x 4 columns]

In [111]:
eu_current_designations = eu_designations.query("jaar == 2023")
eu_current_designations = eu_current_designations.drop(columns=["key_id", "jaar"])
eu_current_designations
data = zwemplekdata.merge(eu_current_designations, left_on="zwemwaterlocatie_id", right_on="zwemwaterlocatie_id", how="left")
data.fillna({'code': 0}, inplace=True)
data

,zwemwaterlocatie_id,naam,korte_naam,status,tekst,info_filename,website,lat,lon,code
0,1323,Engelermeer Oost,Engelermeer Oost,goed,Het Engelermeer is een serie kunstmatige plass...,NB-031-001 Engelermeer Oost.jpg,None,51.7046,5.2461,1
1,1259,'T Hoefsven,'T Hoefsven,goed,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,None,51.6761,5.0942,1
2,1341,'T Nije Hemelriek,'T Nije Hemelriek,goed,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,None,52.9725,6.7556,1
3,1315,'T Schaartven,'T Schaartven,goed,"‘t Schaartven is een voormalige zandwinplas, g...",None,None,51.5735,5.9749,1
4,1344,'T Veenmeer,'T Veenmeer,goed,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,None,53.0829,6.6303,1
...,...,...,...,...,...,...,...,...,...,...
2464,7941840,strand Kortgene Paardekreek,Paardekreek,WAARSCHUWING,Door camping de Paardekreek aangelegd zandstra...,None,None,51.5496,3.8096,1
2465,7356682,strand zoutkamp,None,goed,strand zoutkamp in onderzoek,None,None,53.3388,6.2973,1
2466,6837320,strand zuid Oldambtmeer,strand zuid,goed,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,None,53.1651,7.0372,2
2467,6997562,strandje Brouwershaven,Brouwershaven,goed,Strandje naast jachthaven van Brouwershaven,None,None,51.7315,3.9154,1
2468,1240,t Zwarte Plasje,'t Zwarte Plasje,goed,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,None,51.9593,4.4913,1

### Metingen

In [112]:
measurements = load_wfs_layer("zwr_public:resultaatsen")
measurements = measurements.drop(columns=['id', 'datum_geplande_monstername', 'monitoring_datum_id', 'monitoring_plan_id', 'monster_id', 'type_object_id', 'geometry'])
measurements = measurements.sort_values(["zwemwaterlocatie_id", "object_begin_tijd", "type_object_code"])
measurements = measurements.drop_duplicates(subset=["zwemwaterlocatie_id", "type_object_code"], keep="last")
measurements

,numerieke_waarde,object_begin_tijd,key_id,type_object_code,zwemwaterlocatie_id
4778,80,2024-08-05T07:42:00+00:00,8341296,E_COLI,955
9677,15,2024-08-05T07:42:00+00:00,8341297,INTTNLETRCCN,955
4365,20,2024-07-29T09:03:00+00:00,8328070,E_COLI,956
9264,15,2024-07-29T09:03:00+00:00,8328071,INTTNLETRCCN,956
4366,15,2024-07-29T07:57:00+00:00,8328102,E_COLI,957
...,...,...,...,...,...
9730,30,2024-08-06T10:30:00+00:00,8343485,INTTNLETRCCN,8186460
4564,45,2024-07-30T08:48:00+00:00,8333554,E_COLI,8192060
9464,15,2024-07-30T08:48:00+00:00,8333556,INTTNLETRCCN,8192060
4382,20,2024-07-29T06:20:00+00:00,8328607,E_COLI,8194200
9281,15,2024-07-29T06:20:00+00:00,8328606,INTTNLETRCCN,8194200

In [113]:
measure = measurements.pivot_table(values='numerieke_waarde', index='zwemwaterlocatie_id', columns='type_object_code')
measure

type_object_code     E_COLI  INTTNLETRCCN
zwemwaterlocatie_id
955                      80            15
956                      20            15
957                      15            15
959                      50            60
960                     980           140
...                     ...           ...
8184902                  15            15
8184903                  15            15
8186460                  61            30
8192060                  45            15
8194200                  20            15

[749 rows x 2 columns]

In [114]:
data = data.merge(measure, on="zwemwaterlocatie_id", how="left")
data

,zwemwaterlocatie_id,naam,korte_naam,status,tekst,info_filename,website,lat,lon,code,E_COLI,INTTNLETRCCN
0,1323,Engelermeer Oost,Engelermeer Oost,goed,Het Engelermeer is een serie kunstmatige plass...,NB-031-001 Engelermeer Oost.jpg,None,51.7046,5.2461,1,61.0,30.0
1,1259,'T Hoefsven,'T Hoefsven,goed,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,None,51.6761,5.0942,1,130.0,30.0
2,1341,'T Nije Hemelriek,'T Nije Hemelriek,goed,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,None,52.9725,6.7556,1,15.0,15.0
3,1315,'T Schaartven,'T Schaartven,goed,"‘t Schaartven is een voormalige zandwinplas, g...",None,None,51.5735,5.9749,1,15.0,15.0
4,1344,'T Veenmeer,'T Veenmeer,goed,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,None,53.0829,6.6303,1,15.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2464,7941840,strand Kortgene Paardekreek,Paardekreek,WAARSCHUWING,Door camping de Paardekreek aangelegd zandstra...,None,None,51.5496,3.8096,1,15.0,15.0
2465,7356682,strand zoutkamp,None,goed,strand zoutkamp in onderzoek,None,None,53.3388,6.2973,1,161.0,15.0
2466,6837320,strand zuid Oldambtmeer,strand zuid,goed,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,None,53.1651,7.0372,2,253.0,46.0
2467,6997562,strandje Brouwershaven,Brouwershaven,goed,Strandje naast jachthaven van Brouwershaven,None,None,51.7315,3.9154,1,77.0,15.0
2468,1240,t Zwarte Plasje,'t Zwarte Plasje,goed,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,None,51.9593,4.4913,1,15.0,15.0

### Voorzieningen

In [ ]:
zwemplek_voorziening = load_wfs_layer("zwr_public:zwemplek_voorziening")
zwemplek_voorziening

In [ ]:
voorzieningen = zwemplek_voorziening.groupby('zwemwaterlocatie_id')['voorziening_type_id'].agg(list).reset_index()
voorzieningen

In [ ]:
data = data.merge(voorzieningen, on="zwemwaterlocatie_id", how="left")
data.rename(columns={
    "naam": "name",
    "korte_naam": "alternate_name",
    "status": "current_status",
    "tekst": "description",
    "info_filename": "photos",
    "code": "eu_designation",
    "E_COLI": "e_coli",
    "INTTNLETRCCN": "int_ent",
    "voorziening_type_id": "voorzieningen"
}, inplace=True)
data.set_index("zwemwaterlocatie_id", inplace=True)
data['name'] = data['name']\
    .str.strip()\
    .str.title()\
    .str.replace("^Rcn", "RCN", regex=True)\
    .str.replace("^T ", "'t ", regex=True)\
    .str.replace("['|`]T ", "'t ", regex=True)\
    .str.replace("['|`]S", "'s", regex=True)
data['alternate_name'] = data['alternate_name']\
    .str.strip()\
    .str.title()\
    .str.replace("^Rcn", "RCN", regex=True)\
    .str.replace("^T ", "'t ", regex=True)\
    .str.replace("['|`]T ", "'t ", regex=True)\
    .str.replace("['|`]S", "'s", regex=True)
data

### Waarschuwingen

In [ ]:
preventative_measures = load_wfs_layer("zwr_public:zwemplek_maatregel")
preventative_measures = preventative_measures.drop(columns=['id', 'bw_code', 'object_type', 'toelichtingstandaardextended', 'type', 'geometry', 'zwemplek_naam'])
active_warnings = preventative_measures[(preventative_measures['objectbegintijd'] <= '2024-08-02')]
active_warnings = active_warnings.drop(columns=['redeningetrokken', 'objectbegintijd', 'objecteindtijd', 'omschrijving', 'key_id'])
active_warnings = active_warnings[[
    'zwemwaterlocatie_id', 'toelichtingstandaard', 'toelichtingpubliek']
]
active_warnings.set_index('zwemwaterlocatie_id', inplace=True)
active_warnings.rename(columns={
    'toelichtingstandaard': 'warning_type',
    'toelichtingpubliek': 'warning_description'
}, inplace=True)
active_warnings

In [ ]:
warnings = active_warnings.groupby(['zwemwaterlocatie_id'])[['warning_type','warning_description']].apply(lambda x: x.to_dict('records')).reset_index(name='warnings')
warnings

In [ ]:
data = data.merge(warnings, on="zwemwaterlocatie_id", how="left")
data.rename(columns={
    "zwemwaterlocatie_id": "id",
    "voorzieningen": "amenities"
}, inplace=True)
data

In [ ]:
data.to_json('output.json', orient="records")

In [ ]:
import sqlite3

sql_data = data.copy()
sql_data["amenities"] = sql_data["amenities"].astype(str)
sql_data["warnings"] = sql_data["warnings"].astype(str)
db = sqlite3.connect('../dataset.sqlite3')
sql_data.to_sql('locations', db, index=False, if_exists='append')

In [ ]:
data.columns

# GeoJSON

In [ ]:
from geojson import Feature, Point, FeatureCollection

In [ ]:
collection = []

In [ ]:
for index, row in data.iterrows():
    print(row)
    feature = Feature(id=row['id'],
                      geometry=Point((row['lon'], row['lat'])),
                      properties={
        "name": row['name'],
        "alternate_name": row['alternate_name']
    })
    collection.append(feature)

In [ ]:
geojson = FeatureCollection(collection)

In [ ]:
geojson

In [ ]:
from ipyleaflet import Map, Marker, GeoJSON
import random

center = (52.204793, 360.121558)

m = Map(center=center, zoom=15)

geo_json = GeoJSON(
    data=geojson,
    style={
        'color': 'black'
    }
)
m.layers = [m.layers[0], geo_json]
m