In [1]:
import requests
import pandas as pd
import sqlite3

In [2]:
server = "https://environment.data.gov.uk/doc/bathing-water?_pageSize=1000&_view=bathing-water&_properties=latestProfile.countyName.name%2Cdistrict.alias%2ClatestSampleAssessment.sampleDateTime.ordinalYear%2ClatestComplianceAssessment.sampleYear.ordinalYear%2ClatestComplianceAssessment.assessmentQualifier%2ClatestComplianceAssessment.assessmentRegime&_lang=en%2Ccy%2Cnone&country=http%3A%2F%2Fdata.ordnancesurvey.co.uk%2Fid%2Fcountry%2Fengland&_query-id=XbY01NFqXbY"

In [3]:
data = requests.get(server, headers={"Accept": "application/json, text/javascript, */*; q=0.01"})
result = data.json()['result']['items']

In [4]:
df = pd.json_normalize(data.json()['result']['items'])
df = df.rename(columns={
    "eubwidNotation": "id",
    "name._value": "name",
    "samplingPoint.lat": "lat",
    "samplingPoint.long": "lon"
}).set_index("id")
df['alternate_name'] = df['name']
df

,_about,district,sameAs,sedimentTypesPresent,type,waterQualityImpactedByHeavyRain,yearDesignated,appointedSewerageUndertaker._about,appointedSewerageUndertaker.companyProfile._about,appointedSewerageUndertaker.companyProfile.label,...,latestOpenIncident.expectedEndOfIncident._datatype,latestOpenIncident.incidentNotation,latestOpenIncident.incidentType._about,latestOpenIncident.incidentType.label,latestOpenIncident.nirsRef,latestOpenIncident.som_recordDateTime._value,latestOpenIncident.som_recordDateTime._datatype,latestOpenIncident.startOfIncident._value,latestOpenIncident.startOfIncident._datatype,alternate_name
id,,,,,,,,,,,,,,,,,,,,,
ukc2102-03600,http://environment.data.gov.uk/id/bathing-wate...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,http://environment.data.gov.uk/id/bathing-wate...,http://environment.data.gov.uk/def/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,True,http://reference.data.gov.uk/id/year/1988,http://business.data.gov.uk/id/company/02366703,http://business.data.gov.uk/companies/profile/...,[{'_value': 'Companies House profile for North...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spittal
ukc2102-03700,http://environment.data.gov.uk/id/bathing-wate...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,http://environment.data.gov.uk/id/bathing-wate...,http://environment.data.gov.uk/def/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,False,http://reference.data.gov.uk/id/year/1988,http://business.data.gov.uk/id/company/02366703,http://business.data.gov.uk/companies/profile/...,[{'_value': 'Companies House profile for North...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bamburgh Castle
ukc2102-03800,http://environment.data.gov.uk/id/bathing-wate...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,http://environment.data.gov.uk/id/bathing-wate...,http://environment.data.gov.uk/def/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,False,http://reference.data.gov.uk/id/year/1988,http://business.data.gov.uk/id/company/02366703,http://business.data.gov.uk/companies/profile/...,[{'_value': 'Companies House profile for North...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seahouses North
ukc2102-03900,http://environment.data.gov.uk/id/bathing-wate...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,http://environment.data.gov.uk/id/bathing-wate...,http://environment.data.gov.uk/def/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,False,http://reference.data.gov.uk/id/year/1988,http://business.data.gov.uk/id/company/02366703,http://business.data.gov.uk/companies/profile/...,[{'_value': 'Companies House profile for North...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Beadnell
ukc2101-04000,http://environment.data.gov.uk/id/bathing-wate...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,http://environment.data.gov.uk/id/bathing-wate...,http://environment.data.gov.uk/def/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,False,http://reference.data.gov.uk/id/year/1988,http://business.data.gov.uk/id/company/02366703,http://business.data.gov.uk/companies/profile/...,[{'_value': 'Companies House profile for North...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Low Newton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ukd1230-45775,http://environment.data.gov.uk/id/bathing-wate...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,http://environment.data.gov.uk/id/bathing-wate...,NaN,[http://environment.data.gov.uk/def/bathing-wa...,False,NaN,http://business.data.gov.uk/id/company/02366678,http://business.data.gov.uk/companies/profile/...,[{'_value': 'Companies House profile for Unite...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Coniston Water, Monk Coniston"
ukd1101-45800,http://environment.data.gov.uk/id/bathing-wate...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,http://environment.data.gov.uk/id/bathing-wate...,NaN,[http://environment.data.gov.uk/def/bathing-wa...,False,NaN,http://business.data.gov.uk/id/company/02366678,http://business.data.gov.uk/companies/profile/...,[{'_value': 'Companies House profile for Unite...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Derwent Water at Crow Park
ukd1103-45920,http://environment.data.gov.uk/id/bathing-wate...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,http://environment.data.gov.uk/id/bathing-wate...,[http://environment.data.gov.uk/def/bathing-wa...,[http://environment.data.gov.uk/def/bathing-wa...,True,http://reference.data.gov.uk/id/year/1988,http://business.data.gov.uk/id/company/02366678,http://business.data.gov.uk/companies/profile/...,[{'_value': 'Companies House profile for Unite...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,St Bees
ukd1101-46100,http://environment.data.gov.uk/id/bathing-wate...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,http://environment.data.gov.uk/id/bathing-wate...,[http://environment.data.gov.uk/def/bathing-wa...,[http://environment.data.gov.uk/def/bathing-wa...,True,http://reference.data.gov.uk/id/year/1988,http://business.data.gov.uk/id/company/02366678,http://business.data.gov.uk/companies/profile/...,[{'_value': 'Companies House profile for Unite...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Allonby
ukd4308-46501,http://environment.data.gov.uk/id/bathing-wate...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,http://environment.data.gov.uk/id/bathing-wate...,NaN,[http://environment.data.gov.uk/def/bathing-wa...,False,NaN,http://business.data.gov.uk/id/company/02366678,http://business.data.gov.uk/companies/profile/...,[{'_value': 'Companies House profile for Unite...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,River Ribble at Edisford Bridge

In [5]:
locations = df[[
    "name", "alternate_name", "lat", "lon"
]].copy()

In [6]:
locations

,name,alternate_name,lat,lon
id,,,,
ukc2102-03600,Spittal,Spittal,55.756857,-1.988831
ukc2102-03700,Bamburgh Castle,Bamburgh Castle,55.610951,-1.707903
ukc2102-03800,Seahouses North,Seahouses North,55.590181,-1.666808
ukc2102-03900,Beadnell,Beadnell,55.548751,-1.632288
ukc2101-04000,Low Newton,Low Newton,55.513208,-1.615516
...,...,...,...,...
ukd1230-45775,"Coniston Water, Monk Coniston","Coniston Water, Monk Coniston",54.371790,-3.054350
ukd1101-45800,Derwent Water at Crow Park,Derwent Water at Crow Park,54.594990,-3.142180
ukd1103-45920,St Bees,St Bees,54.489928,-3.608570
ukd1101-46100,Allonby,Allonby,54.768035,-3.434608
ukd4308-46501,River Ribble at Edisford Bridge,River Ribble at Edisford Bridge,53.868470,-2.417280

In [7]:
db = sqlite3.connect("../dataset.sqlite3")
locations.to_sql("locations", db, if_exists="append")

451