In [1]:
import requests
import pandas as pd
import sqlite3

In [2]:
server = "https://environment.data.gov.uk/wales/bathing-waters/doc/bathing-water?_pageSize=1000&_view=bathing-water&_properties=latestProfile.countyName.name%2Cdistrict.alias%2ClatestSampleAssessment.followingSuspension.endOfSuspension%2ClatestSampleAssessment.sampleDateTime.ordinalYear%2ClatestComplianceAssessment.sampleYear.ordinalYear%2ClatestComplianceAssessment.assessmentQualifier%2ClatestComplianceAssessment.assessmentRegime&_lang=en%2Ccy%2Cnone"

In [3]:
data = requests.get(server, headers={"Accept": "application/json, text/javascript, */*; q=0.01"})
result = data.json()['result']['items']

In [4]:
df = pd.json_normalize(data.json()['result']['items'])
df["name"], df["alternate_name"] = [item[1]['_value']
                                    for item in df['name']], [item[0]['_value'] for item in df['name']]
df = df.rename(columns={
    "eubwidNotation": "id",
    "samplingPoint.lat": "lat",
    "samplingPoint.long": "lon"
})
df.set_index("id")

,_about,district,name,regionalOrganization,sameAs,sedimentTypesPresent,type,waterQualityImpactedByHeavyRain,yearDesignated,country._about,...,latestComplianceAssessment.sampleYear.ordinalYear,latestRiskPrediction._about,latestRiskPrediction.expiresAt._value,latestRiskPrediction.expiresAt._datatype,latestRiskPrediction.riskLevel._about,latestRiskPrediction.riskLevel.name._value,latestRiskPrediction.riskLevel.name._lang,yearDesignated._about,yearDesignated.ordinalYear,alternate_name
id,,,,,,,,,,,,,,,,,,,,,
ukl2201-36040,http://environment.data.gov.uk/wales/bathing-w...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,Llanishen Reservoir,http://naturalresources.wales/#nrw,http://environment.data.gov.uk/wales/bathing-w...,http://environment.data.gov.uk/def/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,True,http://reference.data.gov.uk/id/year/2025,http://data.ordnancesurvey.co.uk/id/country/wales,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cronffa Ddwr Llanisien
ukl2202-36050,http://environment.data.gov.uk/wales/bathing-w...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,Thraeth Penarth,http://naturalresources.wales/#nrw,http://environment.data.gov.uk/wales/bathing-w...,http://environment.data.gov.uk/def/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,True,http://reference.data.gov.uk/id/year/2022,http://data.ordnancesurvey.co.uk/id/country/wales,...,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Penarth Beach
ukl2202-36100,http://environment.data.gov.uk/wales/bathing-w...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,"Jacksons Bay, Y Barri",http://naturalresources.wales/#nrw,[http://environment.data.gov.uk/id/bathing-wat...,http://environment.data.gov.uk/def/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,True,http://reference.data.gov.uk/id/year/1988,http://data.ordnancesurvey.co.uk/id/country/wales,...,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jackson's Bay Barry Island
ukl2202-36200,http://environment.data.gov.uk/wales/bathing-w...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,"Whitmore Bay, Y Barri",http://naturalresources.wales/#nrw,[http://environment.data.gov.uk/id/bathing-wat...,http://environment.data.gov.uk/def/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,True,http://reference.data.gov.uk/id/year/1988,http://data.ordnancesurvey.co.uk/id/country/wales,...,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Whitmore Bay Barry Island
ukl2202-36300,http://environment.data.gov.uk/wales/bathing-w...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,"Y Cnap, Y Barri",http://naturalresources.wales/#nrw,[http://environment.data.gov.uk/id/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,[http://environment.data.gov.uk/def/bathing-wa...,True,http://reference.data.gov.uk/id/year/1988,http://data.ordnancesurvey.co.uk/id/country/wales,...,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cold Knap Barry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ukl1301-40500,http://environment.data.gov.uk/wales/bathing-w...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,Kinmel Bay (Sandy Cove),http://naturalresources.wales/#nrw,[http://environment.data.gov.uk/id/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,[http://environment.data.gov.uk/def/bathing-wa...,True,http://reference.data.gov.uk/id/year/1988,http://data.ordnancesurvey.co.uk/id/country/wales,...,2024.0,http://environment.data.gov.uk/wales/bathing-w...,2025-05-26T08:29:00,dateTime,http://environment.data.gov.uk/def/bwq-stp/normal,normal,en,NaN,NaN,Bae Cinmel (Sandy Cove)
ukl1302-40550,http://environment.data.gov.uk/wales/bathing-w...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,"Marine Lake, Y Rhyl",http://naturalresources.wales/#nrw,[http://environment.data.gov.uk/id/bathing-wat...,http://environment.data.gov.uk/def/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,False,http://reference.data.gov.uk/id/year/2012,http://data.ordnancesurvey.co.uk/id/country/wales,...,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Marine Lake, Rhyl"
ukl1302-40600,http://environment.data.gov.uk/wales/bathing-w...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,Y Rhyl Canolog,http://naturalresources.wales/#nrw,[http://environment.data.gov.uk/id/bathing-wat...,http://environment.data.gov.uk/def/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,True,http://reference.data.gov.uk/id/year/1988,http://data.ordnancesurvey.co.uk/id/country/wales,...,2024.0,http://environment.data.gov.uk/wales/bathing-w...,2025-05-26T08:29:00,dateTime,http://environment.data.gov.uk/def/bwq-stp/normal,normal,en,NaN,NaN,Rhyl Central
ukl1302-40650,http://environment.data.gov.uk/wales/bathing-w...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,Y Rhyl - Traeth y Dwyrain,http://naturalresources.wales/#nrw,[http://environment.data.gov.uk/id/bathing-wat...,http://environment.data.gov.uk/def/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,True,http://reference.data.gov.uk/id/year/2014,http://data.ordnancesurvey.co.uk/id/country/wales,...,2024.0,http://environment.data.gov.uk/wales/bathing-w...,2025-05-26T08:29:00,dateTime,http://environment.data.gov.uk/def/bwq-stp/normal,normal,en,NaN,NaN,Rhyl East
ukl1302-40700,http://environment.data.gov.uk/wales/bathing-w...,[{'_about': 'http://data.ordnancesurvey.co.uk/...,Prestatyn Central,http://naturalresources.wales/#nrw,[http://environment.data.gov.uk/id/bathing-wat...,http://environment.data.gov.uk/def/bathing-wat...,[http://environment.data.gov.uk/def/bathing-wa...,True,http://reference.data.gov.uk/id/year/1988,http://data.ordnancesurvey.co.uk/id/country/wales,...,2024.0,http://environment.data.gov.uk/wales/bathing-w...,2025-05-26T08:29:00,dateTime,http://environment.data.gov.uk/def/bwq-stp/normal,normal,en,NaN,NaN,Prestatyn Canolog

In [5]:
locations = df[[
    "id", "name", "alternate_name", "lat", "lon"
]].copy().set_index("id")

In [6]:
locations

,name,alternate_name,lat,lon
id,,,,
ukl2201-36040,Llanishen Reservoir,Cronffa Ddwr Llanisien,51.531213,-3.173303
ukl2202-36050,Thraeth Penarth,Penarth Beach,51.432191,-3.168261
ukl2202-36100,"Jacksons Bay, Y Barri",Jackson's Bay Barry Island,51.391360,-3.263285
ukl2202-36200,"Whitmore Bay, Y Barri",Whitmore Bay Barry Island,51.388367,-3.273982
ukl2202-36300,"Y Cnap, Y Barri",Cold Knap Barry,51.389958,-3.296964
...,...,...,...,...
ukl1301-40500,Kinmel Bay (Sandy Cove),Bae Cinmel (Sandy Cove),53.316513,-3.525563
ukl1302-40550,"Marine Lake, Y Rhyl","Marine Lake, Rhyl",53.312900,-3.500900
ukl1302-40600,Y Rhyl Canolog,Rhyl Central,53.330877,-3.500066
ukl1302-40650,Y Rhyl - Traeth y Dwyrain,Rhyl East,53.325999,-3.486893
ukl1302-40700,Prestatyn Central,Prestatyn Canolog,53.346291,-3.415731

In [7]:
db = sqlite3.connect("../dataset.sqlite3")
locations.to_sql("locations", db, if_exists="append")

112