In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('../../docs/sources/bw_assessment_eea_datahub_1990_2024.xlsx', sheet_name='BWD_data_1990_2024')
df = df.loc[df["season"] == 2024]
df.to_pickle('../../data/EEA_BathingWater_2024.pickle')

In [11]:
bulgaria = df.loc[(df["countryCode"] == "BG") & (df["season"] == 2024)]
bulgaria = bulgaria[[
    "bathingWaterIdentifier",
    "bathingWaterName",
    "lon",
    "lat"
]]
bulgaria.rename({
    "bathingWaterIdentifier": "id",
    "bathingWaterName": "name",
}, axis=1, inplace=True)
bulgaria['name'] = bulgaria['name'].str.title()
bulgaria

                     id                          name      lon      lat
509  BG3242661710017001              Язовир Пчелина 2  26.4707  43.4908
510  BG3310104426003018         Камчия-Плаж Романтика  27.8889  43.0392
511  BG3310507598003020             Бяла-Северен Плаж  27.8978  42.8750
512  BG3310507598003021           Бяла-Централен Плаж  27.8981  42.8725
513  BG3310507598003022               Бяла-Плаж Чайка  27.8981  42.8542
..                  ...                           ...      ...      ...
600  BG3412758356002033           Приморско-Южен Плаж  27.7522  42.2597
601  BG3412758356002034  Международен Младежки Център  27.7533  42.2503
602  BG4251606567009001        Язовир Кърджали-Плаж 1  25.3219  41.6408
603  BG4251615000009002        Язовир Кърджали-Плаж 2  25.3062  41.6468
604  BG4251615268009003        Язовир Студен Кладенец  25.5608  41.6558

[96 rows x 4 columns]

In [12]:
albania = df.loc[(df["countryCode"] == "AL") & (df["season"] == 2024)]
albania = albania[[
    "bathingWaterIdentifier",
    "bathingWaterName",
    "lon",
    "lat"
]]
albania.rename({
    "bathingWaterIdentifier": "id",
    "bathingWaterName": "name",
}, axis=1, inplace=True)
albania['name'] = albania['name'].str.title()
albania

        id      name      lon      lat
0    AL101  Velipoja  19.4100  41.8590
1    AL102  Velipoja  19.4131  41.8615
2    AL103  Velipoja  19.4159  41.8623
3    AL104  Velipoja  19.4240  41.8617
4    AL105  Velipoja  19.4274  41.8611
..     ...       ...      ...      ...
114  AL805   Sarande  20.0138  39.8688
115  AL806   Sarande  20.0204  39.8504
116  AL807    Ksamil  19.9984  39.7732
117  AL808    Ksamil  19.9984  39.7712
118  AL809    Ksamil  19.9980  39.7677

[119 rows x 4 columns]

In [13]:
cyprus = df.loc[(df["countryCode"] == "CY") & (df["season"] == 2024)]
cyprus = cyprus[[
    "bathingWaterIdentifier",
    "bathingWaterName",
    "lon",
    "lat"
]]
cyprus.rename({
    "bathingWaterIdentifier": "id",
    "bathingWaterName": "name",
}, axis=1, inplace=True)
cyprus['name'] = cyprus['name'].str.title()
cyprus

                     id                name      lon      lat
765  CY0001457000000154              Karafa  32.6742  35.1879
766  CY0001457000000155            Kryoneri  32.6911  35.1844
767  CY0001460000000151               Omega  32.6653  35.1923
768  CY0003100000000010              Konnos  34.0696  34.9839
769  CY0003100000000011             Limnara  34.0402  34.9729
..                  ...                 ...      ...      ...
883  CY0006344000000143   Loutra Aphrodites  32.3484  35.0560
884  CY0006344000000145       Xystarokampos  32.3606  35.0470
885  CY0006344000000146  Kampos Tou Souliou  32.3908  35.0414
886  CY000634400000143A            Chalabro  32.3683  35.0453
887  CY0006367000000150        Kanali Pomou  32.5558  35.1756

[123 rows x 4 columns]