In [19]:
import sqlite3
import requests
from xml.etree import ElementTree
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

In [20]:
server = "https://www.wms.nrw.de/wms/elwas-ow?REQUEST=GetFeatureInfo&VERSION=1.1.1&SRS=EPSG:25832&BBOX=-519722.2005900545,5455569.10294,1329442.3876849292,5942320.099060002&WIDTH=1512&HEIGHT=398&LAYERS=badegewaesser_eu&QUERY_LAYERS=badegewaesser_eu&FORMAT=image/png&INFO_FORMAT=application/vnd.ogc.gml&FEATURE_COUNT=500&RADIUS=500&X=787&Y=199&STYLES="

In [21]:
response = requests.get(server)
data = ElementTree.fromstring(response.content)
response.content

b'<?xml version="1.0" encoding="UTF-8"?>\n\n<msGMLOutput \n\t xmlns:gml="http://www.opengis.net/gml"\n\t xmlns:xlink="http://www.w3.org/1999/xlink"\n\t xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n\t<badegewaesser_eu_layer>\n\t<gml:name>Badegew\xc3\xa4sser</gml:name>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>352644.000000,5673856.000000 352644.000000,5673856.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>1</messstelle_id>\n\t\t\t<mst_id_gis>1</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Nord</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>40</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Unterbacher See</badegewaesser_bezeichnung>\n\t\t\t<e32>352644</e32>\n\t\t\t<n32>5673856</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0080</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>352317.000000,5673635.000000 352317.000000,5673635.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>2</messstelle_id>\n\t\t\t<mst_id_gis>2</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>S\xc3\xbcd</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>40</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Unterbacher See</badegewaesser_bezeichnung>\n\t\t\t<e32>352317</e32>\n\t\t\t<n32>5673635</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0081</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>340153.000000,5695735.000000 340153.000000,5695735.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>3</messstelle_id>\n\t\t\t<mst_id_gis>3</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Freibad</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>32</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Kruppsee</badegewaesser_bezeichnung>\n\t\t\t<e32>340153</e32>\n\t\t\t<n32>5695735</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0050</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>346829.000000,5694789.000000 346829.000000,5694789.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>4</messstelle_id>\n\t\t\t<mst_id_gis>4</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Freibad</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>33</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Wolfssee</badegewaesser_bezeichnung>\n\t\t\t<e32>346829</e32>\n\t\t\t<n32>5694789</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0088</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>344826.000000,5692376.000000 344826.000000,5692376.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>5</messstelle_id>\n\t\t\t<mst_id_gis>5</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Freizeitanlage</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>34</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Gro\xc3\x9fenbaumer See</badegewaesser_bezeichnung>\n\t\t\t<e32>344826</e32>\n\t\t\t<n32>5692376</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0041</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>336391.000000,5694797.000000 336391.000000,5694797.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>7</messstelle_id>\n\t\t\t<mst_id_gis>7</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Steg</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>35</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Waldsee</badegewaesser_bezeichnung>\n\t\t\t<e32>336391</e32>\n\t\t\t<n32>5694797</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0084</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>330873.000000,5686935.000000 330873.000000,5686935.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>8</messstelle_id>\n\t\t\t<mst_id_gis>8</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Treppe</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>38</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Neptun</badegewaesser_bezeichnung>\n\t\t\t<e32>330873</e32>\n\t\t\t<n32>5686935</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0066</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>299129.000000,5732006.000000 299129.000000,5732006.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>10</messstelle_id>\n\t\t\t<mst_id_gis>10</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Badestrand</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>22</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Naturfreibad Kessel</badegewaesser_bezeichnung>\n\t\t\t<e32>299129</e32>\n\t\t\t<n32>5732006</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0064</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>313134.000000,5738151.000000 313134.000000,5738151.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>11</messstelle_id>\n\t\t\t<mst_id_gis>11</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Strandbad</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>21</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Wisseler See</badegewaesser_bezeichnung>\n\t\t\t<e32>313134</e32>\n\t\t\t<n32>5738151</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0087</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>318235.000000,5701531.000000 318235.000000,5701531.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>12</messstelle_id>\n\t\t\t<mst_id_gis>12</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Strandbad</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>28</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Eyller See</badegewaesser_bezeichnung>\n\t\t\t<e32>318235</e32>\n\t\t\t<n32>5701531</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0028</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>320039.000000,5742347.000000 320039.000000,5742347.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>13</messstelle_id>\n\t\t\t<mst_id_gis>13</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Badestrand</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>20</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Millinger Meer</badegewaesser_bezeichnung>\n\t\t\t<e32>320039</e32>\n\t\t\t<n32>5742347</n32>\n\t\t\t<guete_opt>2</guete_opt>\n\t\t\t<eu_guete>2</eu_guete>\n\t\t\t<guete_bezeichnung>gute Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>gute Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0057</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>314237.000000,5698577.000000 314237.000000,5698577.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>14</messstelle_id>\n\t\t\t<mst_id_gis>14</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Badestrand</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>29</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Naturfreibad Wachtendonk</badegewaesser_bezeichnung>\n\t\t\t<e32>314237</e32>\n\t\t\t<n32>5698577</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0065</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>310137.000000,5695750.000000 310137.000000,5695750.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>15</messstelle_id>\n\t\t\t<mst_id_gis>15</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Badestrand</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>30</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Wankumer Heidesee</badegewaesser_bezeichnung>\n\t\t\t<e32>310137</e32>\n\t\t\t<n32>5695750</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0085</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>344210.000000,5663713.000000 344210.000000,5663713.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>16</messstelle_id>\n\t\t\t<mst_id_gis>16</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>n\xc3\xb6rdl.Badestrand</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>41</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Nievenheimer See</badegewaesser_bezeichnung>\n\t\t\t<e32>344210</e32>\n\t\t\t<n32>5663713</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0067</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>331220.000000,5678201.000000 331220.000000,5678201.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>17</messstelle_id>\n\t\t\t<mst_id_gis>17</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>n\xc3\xb6rdl.Badestr.</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>39</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Kleiner Kaarster See</badegewaesser_bezeichnung>\n\t\t\t<e32>331220</e32>\n\t\t\t<n32>5678201</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0048</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>341703.000000,5718513.000000 341703.000000,5718513.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>18</messstelle_id>\n\t\t\t<mst_id_gis>18</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Strandbad</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>26</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Tenderingssee</badegewaesser_bezeichnung>\n\t\t\t<e32>341703</e32>\n\t\t\t<n32>5718513</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0076</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>329783.000000,5722195.000000 329783.000000,5722195.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>19</messstelle_id>\n\t\t\t<mst_id_gis>19</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Badestelle</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>25</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Freizeitsee Alpen-Menzelen</badegewaesser_bezeichnung>\n\t\t\t<e32>329783</e32>\n\t\t\t<n32>5722195</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0035</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>333949.000000,5701299.000000 333949.000000,5701299.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>20</messstelle_id>\n\t\t\t<mst_id_gis>20</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Strand</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>31</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Bettenkamper Meer</badegewaesser_bezeichnung>\n\t\t\t<e32>333949</e32>\n\t\t\t<n32>5701299</n32>\n\t\t\t<guete_opt>2</guete_opt>\n\t\t\t<eu_guete>2</eu_guete>\n\t\t\t<guete_bezeichnung>gute Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>gute Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0015</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>333100.000000,5726643.000000 333100.000000,5726643.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>22</messstelle_id>\n\t\t\t<mst_id_gis>22</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Rettungsinsel</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>24</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Auesee</badegewaesser_bezeichnung>\n\t\t\t<e32>333100</e32>\n\t\t\t<n32>5726643</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0004</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>333406.000000,5726776.000000 333406.000000,5726776.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>23</messstelle_id>\n\t\t\t<mst_id_gis>23</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Treibsand</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>24</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Auesee</badegewaesser_bezeichnung>\n\t\t\t<e32>333406</e32>\n\t\t\t<n32>5726776</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0005</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>322960.000000,5729195.000000 322960.000000,5729195.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>24</messstelle_id>\n\t\t\t<mst_id_gis>24</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Nichtschwimmer</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>23</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Naturbad Xanten-Wardt</badegewaesser_bezeichnung>\n\t\t\t<e32>322960</e32>\n\t\t\t<n32>5729195</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0062</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>323118.000000,5729116.000000 323118.000000,5729116.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>25</messstelle_id>\n\t\t\t<mst_id_gis>25</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Schwimmer</messstelle_bezeichnung>\n\t\t\t<badegewaesser_id>23</badegewaesser_id>\n\t\t\t<badegewaesser_bezeichnung>Naturbad Xanten-Wardt</badegewaesser_bezeichnung>\n\t\t\t<e32>323118</e32>\n\t\t\t<n32>5729116</n32>\n\t\t\t<guete_opt>1</guete_opt>\n\t\t\t<eu_guete>1</eu_guete>\n\t\t\t<guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</guete_bezeichnung>\n\t\t\t<eu_guete_bezeichnung>ausgezeichnete Wasserqualit\xc3\xa4t</eu_guete_bezeichnung>\n\t\t\t<bathingwaterid>DENW_PR_0063</bathingwaterid>\n\t\t</badegewaesser_eu_feature>\n\t\t<badegewaesser_eu_feature>\n\t\t\t<gml:boundedBy>\n\t\t\t\t<gml:Box srsName="EPSG:25832">\n\t\t\t\t\t<gml:coordinates>354189.000000,5654201.000000 354189.000000,5654201.000000</gml:coordinates>\n\t\t\t\t</gml:Box>\n\t\t\t</gml:boundedBy>\n\t\t\t<messstelle_id>26</messstelle_id>\n\t\t\t<mst_id_gis>26</mst_id_gis>\n\t\t\t<messstelle_bezeichnung>Freibad</messstelle_bez

In [22]:
locationData = []
namespaces = {
    'gml': 'http://www.opengis.net/gml'
}


for location in data[0].findall('badegewaesser_eu_feature'):
    id = location.find('messstelle_id').text
    name = location.find('badegewaesser_bezeichnung').text
    alternate_name = ' '.join([name, location.find('messstelle_bezeichnung').text])
    bbox = location.find('./gml:boundedBy/gml:Box/gml:coordinates', namespaces=namespaces).text
    coords = bbox.split(" ")[0].split(",")
    locationData.append([
        id, name, alternate_name, 
        Point(coords[0], coords[1])
    ])

In [23]:
df = gpd.GeoDataFrame(locationData, columns=["id", "name", "alternate_name", "bbox"])\
.set_index('id')
df

,name,alternate_name,bbox
id,,,
1,Unterbacher See,Unterbacher See Nord,POINT (352644 5673856)
2,Unterbacher See,Unterbacher See Süd,POINT (352317 5673635)
3,Kruppsee,Kruppsee Freibad,POINT (340153 5695735)
4,Wolfssee,Wolfssee Freibad,POINT (346829 5694789)
5,Großenbaumer See,Großenbaumer See Freizeitanlage,POINT (344826 5692376)
...,...,...,...
117,Ruhr,Ruhr Schwimmstelle Mülheim an der Ruhr,POINT (353473 5697308)
115,Ruhr,Ruhr Ruhrwiesen in Linden-Dahlhausen,POINT (370614 5698755)
118,Esmecke-Stausee (Einbergsee),Esmecke-Stausee (Einbergsee) Badestelle,POINT (441236 5683083)
119,Fühlinger See,Fühlinger See Badestelle See 1,POINT (353472 5655270)
120,Fühlinger See,Fühlinger See Badestelle See 7,POINT (355216 5654462)

In [24]:
df = df.set_geometry('bbox')
df = df.set_crs('25832')

In [25]:
df.crs

<Projected CRS: EPSG:25832>
Name: ETRS89 / UTM zone 32N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Europe between 6°E and 12°E: Austria; Belgium; Denmark - onshore and offshore; Germany - onshore and offshore; Norway including - onshore and offshore; Spain - offshore.
- bounds: (6.0, 38.76, 12.01, 84.33)
Coordinate Operation:
- name: UTM zone 32N
- method: Transverse Mercator
Datum: European Terrestrial Reference System 1989 ensemble
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [26]:
df

,name,alternate_name,bbox
id,,,
1,Unterbacher See,Unterbacher See Nord,POINT (352644 5673856)
2,Unterbacher See,Unterbacher See Süd,POINT (352317 5673635)
3,Kruppsee,Kruppsee Freibad,POINT (340153 5695735)
4,Wolfssee,Wolfssee Freibad,POINT (346829 5694789)
5,Großenbaumer See,Großenbaumer See Freizeitanlage,POINT (344826 5692376)
...,...,...,...
117,Ruhr,Ruhr Schwimmstelle Mülheim an der Ruhr,POINT (353473 5697308)
115,Ruhr,Ruhr Ruhrwiesen in Linden-Dahlhausen,POINT (370614 5698755)
118,Esmecke-Stausee (Einbergsee),Esmecke-Stausee (Einbergsee) Badestelle,POINT (441236 5683083)
119,Fühlinger See,Fühlinger See Badestelle See 1,POINT (353472 5655270)
120,Fühlinger See,Fühlinger See Badestelle See 7,POINT (355216 5654462)

In [27]:
df = df.to_crs('4326')
df

,name,alternate_name,bbox
id,,,
1,Unterbacher See,Unterbacher See Nord,POINT (6.89095 51.19709)
2,Unterbacher See,Unterbacher See Süd,POINT (6.88637 51.19502)
3,Kruppsee,Kruppsee Freibad,POINT (6.70253 51.39031)
4,Wolfssee,Wolfssee Freibad,POINT (6.79881 51.38365)
5,Großenbaumer See,Großenbaumer See Freizeitanlage,POINT (6.7711 51.36142)
...,...,...,...
117,Ruhr,Ruhr Schwimmstelle Mülheim an der Ruhr,POINT (6.89318 51.40804)
115,Ruhr,Ruhr Ruhrwiesen in Linden-Dahlhausen,POINT (7.13896 51.42521)
118,Esmecke-Stausee (Einbergsee),Esmecke-Stausee (Einbergsee) Badestelle,POINT (8.15716 51.29603)
119,Fühlinger See,Fühlinger See Badestelle See 1,POINT (6.91035 51.03028)
120,Fühlinger See,Fühlinger See Badestelle See 7,POINT (6.93552 51.02346)

In [28]:
locations = df.copy()
locations['lon'] = df.bbox.apply(lambda p: p.x)
locations['lat'] = df.bbox.apply(lambda p: p.y)
locations = locations.drop(columns=['bbox'])
locations

,name,alternate_name,lon,lat
id,,,,
1,Unterbacher See,Unterbacher See Nord,6.890953,51.197087
2,Unterbacher See,Unterbacher See Süd,6.886367,51.195016
3,Kruppsee,Kruppsee Freibad,6.702527,51.390308
4,Wolfssee,Wolfssee Freibad,6.798811,51.383650
5,Großenbaumer See,Großenbaumer See Freizeitanlage,6.771103,51.361424
...,...,...,...,...
117,Ruhr,Ruhr Schwimmstelle Mülheim an der Ruhr,6.893180,51.408039
115,Ruhr,Ruhr Ruhrwiesen in Linden-Dahlhausen,7.138962,51.425213
118,Esmecke-Stausee (Einbergsee),Esmecke-Stausee (Einbergsee) Badestelle,8.157162,51.296033
119,Fühlinger See,Fühlinger See Badestelle See 1,6.910345,51.030280
120,Fühlinger See,Fühlinger See Badestelle See 7,6.935522,51.023461

In [29]:
db = sqlite3.connect("../dataset.sqlite3")
locations.to_sql("locations", db, if_exists="append")

115