In [19]:
import requests

In [20]:
import pandas as pd

In [21]:
def fetch_bathing_sites():
    url = (
        "https://utility.arcgis.com/usrsvcs/servers/"
        "7535042c1bf84078a5af5e14acb7604d/rest/services/"
        "EHD_BathingSitesJoined_PublicView_/FeatureServer/0/query"
    )

    params = {
        "f": "pjson",
        "outFields": (
            "BC_Class,Bathing_Water_Profile,Blue_Flag_OR_Beach_of_Quality,Description,"
            "EU_Class,Local_Council,Name_ENG,Name_MT,Pet_Friendly,Press_Release_Link,"
            "RecommendedForBathing_YES_OR_NO,Remarks,Sandy_OR_Rocky_Beach,Site_Code,"
            "Zone,ObjectId,GlobalID"
        ),
        "outSR": "4326",
        "returnM": "true",
        "returnZ": "true",
        "spatialRel": "esriSpatialRelIntersects",
        "where": "1=1",
    }

    headers = {
        "accept": "*/*",
        "accept-language": "nl,en;q=0.9",
        "cache-control": "no-cache",
        "origin": "https://mfh-mt.maps.arcgis.com",
        "pragma": "no-cache",
        "priority": "u=1, i",
        "referer": "https://mfh-mt.maps.arcgis.com/apps/dashboards/31f48638f89c4d60bd6143818a46a2c7",
        'sec-ch-ua': '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"',
        "sec-ch-ua-mobile": "?0",
        'sec-ch-ua-platform': '"macOS"',
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-site",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36",
    }

    response = requests.get(url, params=params, headers=headers, timeout=30)
    response.raise_for_status()
    return response.json()

In [22]:
data = fetch_bathing_sites()
data

{'objectIdFieldName': 'ObjectId',
 'uniqueIdField': {'name': 'ObjectId', 'isSystemMaintained': True},
 'globalIdFieldName': 'GlobalID',
 'hasZ': True,
 'geometryType': 'esriGeometryPoint',
 'spatialReference': {'wkid': 4326, 'latestWkid': 4326},
 'fields': [{'name': 'BC_Class',
   'type': 'esriFieldTypeString',
   'alias': 'BC_Class',
   'sqlType': 'sqlTypeOther',
   'length': 255,
   'domain': {'type': 'codedValue',
    'name': 'BC Class',
    'mergePolicy': 'esriMPTDefaultValue',
    'splitPolicy': 'esriSPTDefaultValue',
    'codedValues': [{'name': 'Excellent', 'code': '1 - Excellent'},
     {'name': 'Good', 'code': '2 - Good'},
     {'name': 'Sufficient', 'code': '3 - Sufficient'},
     {'name': 'Poor', 'code': '4 - Poor'},
     {'name': 'Closed', 'code': '5 - Closed'},
     {'name': 'Other', 'code': '6 - Other'}]},
   'defaultValue': None},
  {'name': 'Bathing_Water_Profile',
   'type': 'esriFieldTypeString',
   'alias': 'Bathing Water Profile ',
   'sqlType': 'sqlTypeOther',
   'length': 150,
   'domain': None,
   'defaultValue': None},
  {'name': 'Blue_Flag_OR_Beach_of_Quality',
   'type': 'esriFieldTypeString',
   'alias': 'Blue Flag or Blue Beach',
   'sqlType': 'sqlTypeOther',
   'length': 55,
   'domain': None,
   'defaultValue': None},
  {'name': 'Description',
   'type': 'esriFieldTypeString',
   'alias': 'Description',
   'sqlType': 'sqlTypeOther',
   'length': 500,
   'domain': None,
   'defaultValue': None},
  {'name': 'EU_Class',
   'type': 'esriFieldTypeString',
   'alias': 'EU Class',
   'sqlType': 'sqlTypeOther',
   'length': 255,
   'domain': {'type': 'codedValue',
    'name': 'EU Class',
    'mergePolicy': 'esriMPTDefaultValue',
    'splitPolicy': 'esriSPTDefaultValue',
    'codedValues': [{'name': 'Excellent', 'code': '1 - Excellent'},
     {'name': 'Good', 'code': '2 - Good'},
     {'name': 'Sufficient', 'code': '3 - Sufficient'},
     {'name': 'Poor', 'code': '4 - Poor'},
     {'name': 'Closed', 'code': '5 - Closed'},
     {'name': 'Other', 'code': '6 - Other'}]},
   'defaultValue': None},
  {'name': 'Local_Council',
   'type': 'esriFieldTypeString',
   'alias': 'Local Council',
   'sqlType': 'sqlTypeOther',
   'length': 55,
   'domain': None,
   'defaultValue': None},
  {'name': 'Name_ENG',
   'type': 'esriFieldTypeString',
   'alias': 'Name ENG',
   'sqlType': 'sqlTypeOther',
   'length': 55,
   'domain': None,
   'defaultValue': None},
  {'name': 'Name_MT',
   'type': 'esriFieldTypeString',
   'alias': 'Name MT',
   'sqlType': 'sqlTypeOther',
   'length': 55,
   'domain': None,
   'defaultValue': None},
  {'name': 'Pet_Friendly',
   'type': 'esriFieldTypeString',
   'alias': 'Pet Friendly',
   'sqlType': 'sqlTypeOther',
   'length': 55,
   'domain': None,
   'defaultValue': None},
  {'name': 'Press_Release_Link',
   'type': 'esriFieldTypeString',
   'alias': 'Press Release Link',
   'sqlType': 'sqlTypeOther',
   'length': 255,
   'domain': None,
   'defaultValue': None},
  {'name': 'RecommendedForBathing_YES_OR_NO',
   'type': 'esriFieldTypeString',
   'alias': 'Recommended for Bathing ',
   'sqlType': 'sqlTypeOther',
   'length': 55,
   'domain': None,
   'defaultValue': None},
  {'name': 'Remarks',
   'type': 'esriFieldTypeString',
   'alias': 'Remarks',
   'sqlType': 'sqlTypeOther',
   'length': 255,
   'domain': None,
   'defaultValue': None},
  {'name': 'Sandy_OR_Rocky_Beach',
   'type': 'esriFieldTypeString',
   'alias': 'Sandy / Rocky Beach',
   'sqlType': 'sqlTypeOther',
   'length': 55,
   'domain': None,
   'defaultValue': None},
  {'name': 'Site_Code',
   'type': 'esriFieldTypeString',
   'alias': 'Site Code',
   'sqlType': 'sqlTypeOther',
   'length': 55,
   'domain': None,
   'defaultValue': None},
  {'name': 'Zone',
   'type': 'esriFieldTypeString',
   'alias': 'Zone',
   'sqlType': 'sqlTypeOther',
   'length': 255,
   'domain': None,
   'defaultValue': None},
  {'name': 'ObjectId',
   'type': 'esriFieldTypeOID',
   'alias': 'ObjectId',
   'sqlType': 'sqlTypeOther',
   'length': 8,
   'domain': None,
   'defaultValue': None},
  {'name': 'GlobalID',
   'type': 'esriFieldTypeGlobalID',
   'alias': 'GlobalID',
   'sqlType': 'sqlTypeOther',
   'length': 38,
   'domain': None,
   'defaultValue': None}],
 'exceededTransferLimit': True,
 'features': [{'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 1,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 2,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 3,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 4,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 5,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 6,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 7,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 8,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 9,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 10,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 11,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 12,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 13,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 14,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 15,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',
    'Bathing_Water_Profile': 'https://environmentalhealth.gov.mt/en/ehs/wrau/bathing-water-profiles/bwp-1-xaghjra/',
    'Blue_Flag_OR_Beach_of_Quality': 'No',
    'Description': 'Located along Malta’s southern coast in the village of Xghajra, adjacent to the promenade Triq Dawret ix-Xatt. A rocky beach typical to the Maltese Coast surrounded by coastal garrigues, natural vegetation and concrete platforms with a slipway.',
    'EU_Class': '1 - Excellent',
    'Local_Council': 'Xghajra',
    'Name_ENG': 'Kalanka tal-Irgiel',
    'Name_MT': 'Il-Kalanka tal-Irgiel',
    'Pet_Friendly': 'No',
    'Press_Release_Link': None,
    'RecommendedForBathing_YES_OR_NO': 'Yes',
    'Remarks': None,
    'Sandy_OR_Rocky_Beach': 'Rocky beach',
    'Site_Code': 'A01',
    'Zone': 'A',
    'ObjectId': 16,
    'GlobalID': 'ed761b96-f2d7-4655-8b10-ceb8d2582d66'},
   'geometry': {'x': 14.546710999845134, 'y': 35.88913200041982, 'z': 0}},
  {'attributes': {'BC_Class': '1 - Excellent',

In [23]:
df = pd.json_normalize(data['features'])

In [24]:
df

,attributes.BC_Class,attributes.Bathing_Water_Profile,attributes.Blue_Flag_OR_Beach_of_Quality,attributes.Description,attributes.EU_Class,attributes.Local_Council,attributes.Name_ENG,attributes.Name_MT,attributes.Pet_Friendly,attributes.Press_Release_Link,attributes.RecommendedForBathing_YES_OR_NO,attributes.Remarks,attributes.Sandy_OR_Rocky_Beach,attributes.Site_Code,attributes.Zone,attributes.ObjectId,attributes.GlobalID,geometry.x,geometry.y,geometry.z
0,1 - Excellent,https://environmentalhealth.gov.mt/en/ehs/wrau...,No,Located along Malta’s southern coast in the vi...,1 - Excellent,Xghajra,Kalanka tal-Irgiel,Il-Kalanka tal-Irgiel,No,NaN,Yes,NaN,Rocky beach,A01,A,1,ed761b96-f2d7-4655-8b10-ceb8d2582d66,14.546711,35.889132,0
1,1 - Excellent,https://environmentalhealth.gov.mt/en/ehs/wrau...,No,Located along Malta’s southern coast in the vi...,1 - Excellent,Xghajra,Kalanka tal-Irgiel,Il-Kalanka tal-Irgiel,No,NaN,Yes,NaN,Rocky beach,A01,A,2,ed761b96-f2d7-4655-8b10-ceb8d2582d66,14.546711,35.889132,0
2,1 - Excellent,https://environmentalhealth.gov.mt/en/ehs/wrau...,No,Located along Malta’s southern coast in the vi...,1 - Excellent,Xghajra,Kalanka tal-Irgiel,Il-Kalanka tal-Irgiel,No,NaN,Yes,NaN,Rocky beach,A01,A,3,ed761b96-f2d7-4655-8b10-ceb8d2582d66,14.546711,35.889132,0
3,1 - Excellent,https://environmentalhealth.gov.mt/en/ehs/wrau...,No,Located along Malta’s southern coast in the vi...,1 - Excellent,Xghajra,Kalanka tal-Irgiel,Il-Kalanka tal-Irgiel,No,NaN,Yes,NaN,Rocky beach,A01,A,4,ed761b96-f2d7-4655-8b10-ceb8d2582d66,14.546711,35.889132,0
4,1 - Excellent,https://environmentalhealth.gov.mt/en/ehs/wrau...,No,Located along Malta’s southern coast in the vi...,1 - Excellent,Xghajra,Kalanka tal-Irgiel,Il-Kalanka tal-Irgiel,No,NaN,Yes,NaN,Rocky beach,A01,A,5,ed761b96-f2d7-4655-8b10-ceb8d2582d66,14.546711,35.889132,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2 - Good,https://environmentalhealth.gov.mt/en/ehs/wrau...,Yes,Located along Malta’s northern coast in Triq l...,2 - Good,Mellieha,Ghadira Bay near picnic area,Il-Bajja tal-Mellieha hdejn iz-Zona tal-piknik,No,NaN,Yes,NaN,Sandy beach,C13,C,1996,d78a4c3f-598f-4cee-90d1-dcf076b27e62,14.352315,35.967669,0
1996,2 - Good,https://environmentalhealth.gov.mt/en/ehs/wrau...,Yes,Located along Malta’s northern coast in Triq l...,2 - Good,Mellieha,Ghadira Bay near picnic area,Il-Bajja tal-Mellieha hdejn iz-Zona tal-piknik,No,NaN,Yes,NaN,Sandy beach,C13,C,1997,d78a4c3f-598f-4cee-90d1-dcf076b27e62,14.352315,35.967669,0
1997,2 - Good,https://environmentalhealth.gov.mt/en/ehs/wrau...,Yes,Located along Malta’s northern coast in Triq l...,2 - Good,Mellieha,Ghadira Bay near picnic area,Il-Bajja tal-Mellieha hdejn iz-Zona tal-piknik,No,NaN,Yes,NaN,Sandy beach,C13,C,1998,d78a4c3f-598f-4cee-90d1-dcf076b27e62,14.352315,35.967669,0
1998,2 - Good,https://environmentalhealth.gov.mt/en/ehs/wrau...,Yes,Located along Malta’s northern coast in Triq l...,2 - Good,Mellieha,Ghadira Bay near picnic area,Il-Bajja tal-Mellieha hdejn iz-Zona tal-piknik,No,NaN,Yes,NaN,Sandy beach,C13,C,1999,d78a4c3f-598f-4cee-90d1-dcf076b27e62,14.352315,35.967669,0
1999,2 - Good,https://environmentalhealth.gov.mt/en/ehs/wrau...,Yes,Located along Malta’s northern coast in Triq l...,2 - Good,Mellieha,Ghadira Bay near picnic area,Il-Bajja tal-Mellieha hdejn iz-Zona tal-piknik,No,NaN,Yes,NaN,Sandy beach,C13,C,2000,d78a4c3f-598f-4cee-90d1-dcf076b27e62,14.352315,35.967669,0

In [25]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(df):
    # Drop duplicate rows in column: 'attributes.Site_Code'
    df = df.drop_duplicates(subset=['attributes.Site_Code'])
    return df

df_clean = clean_data(df.copy())
df_clean.head()

,attributes.BC_Class,attributes.Bathing_Water_Profile,attributes.Blue_Flag_OR_Beach_of_Quality,attributes.Description,attributes.EU_Class,attributes.Local_Council,attributes.Name_ENG,attributes.Name_MT,attributes.Pet_Friendly,attributes.Press_Release_Link,attributes.RecommendedForBathing_YES_OR_NO,attributes.Remarks,attributes.Sandy_OR_Rocky_Beach,attributes.Site_Code,attributes.Zone,attributes.ObjectId,attributes.GlobalID,geometry.x,geometry.y,geometry.z
0,1 - Excellent,https://environmentalhealth.gov.mt/en/ehs/wrau...,No,Located along Malta’s southern coast in the vi...,1 - Excellent,Xghajra,Kalanka tal-Irgiel,Il-Kalanka tal-Irgiel,No,NaN,Yes,NaN,Rocky beach,A01,A,1,ed761b96-f2d7-4655-8b10-ceb8d2582d66,14.546711,35.889132,0
46,1 - Excellent,https://environmentalhealth.gov.mt/en/ehs/wrau...,No,Located along Malta’s southern coast in the vi...,1 - Excellent,Xghajra,Xghajra Beach,Il-Bajja ta' Xghajra,No,NaN,Yes,NaN,Rocky beach,A02,A,47,44a89b76-6599-432a-8d45-4f2ccee0c9b4,14.552478,35.885501,0
92,1 - Excellent,https://environmentalhealth.gov.mt/en/ehs/wrau...,No,Located along Malta’s southern coast in the vi...,1 - Excellent,Marsascala,Zonqor Street opp San Nikola Street,Triq iz-Zonqor opp Triq San Nikola,No,NaN,Yes,NaN,Rocky beach,A04,A,93,a1bdca16-3f96-4517-b37a-a9f0578175db,14.566421,35.865723,0
138,1 - Excellent,https://environmentalhealth.gov.mt/en/ehs/wrau...,No,Located along Malta’s southern coast in the vi...,1 - Excellent,Marsascala,Zonqor Street next to jetty,Triq iz-Zonqor biswit il-moll,No,NaN,Yes,NaN,Rocky beach,A03,A,139,f3e3a14a-5866-46d5-b423-44e0d34c95c6,14.567590,35.866510,0
184,1 - Excellent,https://environmentalhealth.gov.mt/en/ehs/wrau...,No,Located along Malta’s southern coast in the vi...,1 - Excellent,Marsascala,Salini Street,Triq is-Salini,No,NaN,Yes,NaN,Rocky beach,A05,A,185,769eb429-84c5-400b-b9da-000c3c7fe2ff,14.568560,35.864926,0

In [26]:
dataset = df_clean[[
    'attributes.Site_Code',
    'attributes.Name_ENG',
    'geometry.x',
    'geometry.y'
]]
dataset.rename(mapper={
    'attributes.Site_Code': 'id',
    'attributes.Name_ENG': 'name',
    'geometry.x': 'lon',
    'geometry.y': 'lat'
}, axis=1, inplace=True)

In [27]:
dataset

,id,name,lon,lat
0,A01,Kalanka tal-Irgiel,14.546711,35.889132
46,A02,Xghajra Beach,14.552478,35.885501
92,A04,Zonqor Street opp San Nikola Street,14.566421,35.865723
138,A03,Zonqor Street next to jetty,14.567590,35.866510
184,A05,Salini Street,14.568560,35.864926
230,A06,Jerma Bay,14.574268,35.861668
276,A07,Fajtata,14.566521,35.854971
322,A08,St Thomas Bay,14.563275,35.852743
368,A09,Ghar Ahmar Bay,14.545228,35.834404
414,A10,Qajjenza Street opp Ghannejja street,14.536054,35.832666
460,A11,F.M. Ferretti street opp S. Cachia Zammit street,14.534517,35.832169
506,A12,St Georges Bay,14.530782,35.832328
552,A13,opp Liquid Fuel Depot.,14.533141,35.828246
598,A14,Pretty Bay on the left,14.530281,35.825441
644,A15,Pretty Bay on the right,14.529495,35.824189
690,A16,Wied iz-Zurrieq,14.451576,35.819957
736,A17,Ghar Lapsi,14.423610,35.827074
782,B01,Bahar Ic-Caghaq near the public toilets,14.456252,35.939968
828,B02,Pembroke Pool,14.485499,35.931609
874,B03,St. George's Bay left side,14.487702,35.926459
920,B04,St. George's Bay right side,14.488490,35.925396
966,B05,Near Wilga Street,14.493126,35.923583
1012,B06,End of Spinola Street,14.494978,35.919395
1058,B07,next to St. Julian's Waterpolo Club,14.493523,35.917406
1104,B08,Balluta Bay left side,14.493621,35.914758
1150,B09,Balluta Bay right side,14.494597,35.914940
1196,B10,Exiles Bay- sandy beach,14.496997,35.915543
1242,B11,Exiles beach next to children's playground,14.498429,35.918350
1288,B12,Fond Ghadir Beach,14.504721,35.915663
1334,B13,next to Sliema Pitch,14.507557,35.913771
1380,B14,Qui-Si-Sana beach,14.508329,35.911376
1426,B15,Qui-Si-Sana near playground,14.511106,35.909283
1472,C01,Gnejna Bay,14.343810,35.921189
1518,C02,Ghajn Tuffieha bay left side,14.343021,35.927889
1564,C03,Ghajn Tuffieha bay right side,14.344680,35.930002
1610,C04,Golden Bay left side,14.344538,35.933030
1656,C05,Golden bay right side,14.343174,35.934509
1702,C06,Anchor Bay,14.340128,35.960081
1748,C07,Paradise Bay,14.332427,35.981976
1794,C08,Cirkewwa Bay,14.331050,35.987385
1840,C09,Armier,14.355835,35.989789
1886,C10,Little Armier Beach,14.359386,35.990180
1932,C12,Ghadira Bay opposite Nature Reserve,14.350883,35.969191
1978,C13,Ghadira Bay near picnic area,14.352315,35.967669