In [1]:
import requests
import pandas as pd
import sqlite3

server = "https://www.ages.at/typo3temp/badegewaesser_db.json"

In [2]:
response = requests.get(server)
details = response.json()
data = []
for item in details["BUNDESLAENDER"]: 
    data = data + item['BADEGEWAESSER']

for item in data:     
    name = item["BADEGEWAESSERNAME"]
    values = item["MESSWERTE"][0]
    E_COLI, Int_Ent, Temp = values["E"], values["E_C"], values["W"]

    print(f"{name}: \nE.Coli: {E_COLI} KBE/100ml\nIntestinal Enterococci: {Int_Ent} KBE/100ml\nTemperature: {Temp}°C\n")

Naturbadesee Königsdorf:
E.Coli: 21 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 26°C

Sonnensee Ritzing:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.7°C

Neusiedlersee, Rust:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 19.3°C

Neusiedlersee, Breitenbrunn:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 18.3°C

Neusiedlersee, Mörbisch:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 19.2°C

Neufelder See:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.5°C

Steinbrunner See:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.2°C

Stausee Forchtenstein:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.2°C

Badesee Neudörfl:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24°C

Römersee Wiesen:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.8°C

Badesee Andau:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.2°C

Badesee Apetlon:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.1°C

Neusiedlersee, Illmitz:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 18°C

Neusiedlersee, Neusiedl:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 19.1°C

Neusiedlersee, Podersdorf:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 18.5°C

Neusiedlersee, Weiden:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 30 KBE/100ml
Temperature: 18.9°C

Stausee Rauchwart:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 26.3°C

Stausee Burg, Hannersdorf:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.1°C

Stausee Rechnitz:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.8°C

Stausee Neustift/Lafnitz:
E.Coli: 122 KBE/100ml
Intestinal Enterococci: 98 KBE/100ml
Temperature: 22.5°C

Ausee 1, Blindenmarkt:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25°C

Ausee 2, Blindenmarkt:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25°C

Ausee 3, Blindenmarkt:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.4°C

Donau Altarm, Weitenegg:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 127 KBE/100ml
Temperature: 22.5°C

Lunzer See, Lunz:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.1°C

Ratzersdorfer See:
E.Coli: 77 KBE/100ml
Intestinal Enterococci: 144 KBE/100ml
Temperature: 23.4°C

Ebersdorfer See:
E.Coli: 93 KBE/100ml
Intestinal Enterococci: 77 KBE/100ml
Temperature: 23.9°C

Badesee, Traismauer:
E.Coli: 93 KBE/100ml
Intestinal Enterococci: 110 KBE/100ml
Temperature: 23.1°C

Herrenteich, Litschau:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.3°C

Edlerseeteich, Geras:
E.Coli: 270 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.7°C

Badeteich, Horn:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.5°C

Bergwerksee, Langau:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.6°C

Thurnberger Stausee, Idolsberg:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.6°C

Badeteich, Allentsteig:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.2°C

Frauenwieserteich, Langschlag:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.4°C

Dobrastausee, Pölla:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.4°C

Waldbad, Rappottenstein:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.4°C

Stausee, Ottenstein:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.3°C

Badeteich, Hohenau:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24°C

Badeteich, Poysdorf:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 375 KBE/100ml
Temperature: 23.4°C

Badeteich Seeschlacht, Langenzersdorf:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 442 KBE/100ml
Temperature: 24.6°C

Aubad, Tulln:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 371 KBE/100ml
Temperature: 23.8°C

Donau Altarm, Greifenstein:
E.Coli: 30 KBE/100ml
Intestinal Enterococci: 160 KBE/100ml
Temperature: 23°C

Badeteich, Gerasdorf:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.7°C

Erholungszentrum, Oberwaltersdorf:
E.Coli: 30 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.9°C

Ozeanteich, Guntramsdorf:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.5°C

Windradlteich, Guntramsdorf:
E.Coli: 46 KBE/100ml
Intestinal Enterococci: 45 KBE/100ml
Temperature: 25.7°C

Kahrteich, Wr. Neudorf:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.6°C

Alte Donau, Angelibad:
E.Coli: 61 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.9°C

Neue Donau, oberhalb Nordbahnbrücke:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.5°C

Neue Donau, Höhe Grundwasserwerk:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.4°C

Neue Donau, Höhe Segelhafen:
E.Coli: 30 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.7°C

Alte Donau, Gänsehäufel Ost:
E.Coli: 30 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.1°C

Alte Donau, Gänsehäufel Süd:
E.Coli: 30 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22°C

Alte Donau, Gänsehäufel West:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.6°C

Alte Donau, Kaiserwasser:
E.Coli: 30 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21°C

Alte Donau, Strandbad:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.3°C

Untere Alte Donau:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.9°C

Neue Donau, Höhe Lobgrundstraße:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 94 KBE/100ml
Temperature: 24.6°C

Neue Donau, stromauf Wasserskilift:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.9°C

Neue Donau, stromab Ostbahnbrücke:
E.Coli: 77 KBE/100ml
Intestinal Enterococci: 943 KBE/100ml
Temperature: 23.4°C

Neue Donau, stromab Reichsbrücke:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.9°C

Neue Donau, stromab Steinspornbrücke:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.7°C

Neue Donau, stromauf Wehr 2:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 77 KBE/100ml
Temperature: 24.9°C

Mühlwasser, Strandbad Stadlau:
E.Coli: 46 KBE/100ml
Intestinal Enterococci: 77 KBE/100ml
Temperature: 20.6°C

Wörthersee, Klagenfurt:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 30 KBE/100ml
Temperature: 25°C

Wörthersee, Maiernigg:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25°C

Faaker See, Drobollach:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.7°C

Ossiacher See, Heiligengestade:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.8°C

Keutschacher See, Südwest:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.9°C

Keutschacher See, Keutschach:
E.Coli: 30 KBE/100ml
Intestinal Enterococci: 30 KBE/100ml
Temperature: 25°C

Wörthersee, Reifnitz:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25°C

Wörthersee, Pörtschach:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25°C

Wörthersee, Saag:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25°C

Afritzer See, Südost:
E.Coli: 127 KBE/100ml
Intestinal Enterococci: 268 KBE/100ml
Temperature: 23°C

Afritzer See, Südwest:
E.Coli: 77 KBE/100ml
Intestinal Enterococci: 61 KBE/100ml
Temperature: 23°C

Feldsee, Feld am See:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.5°C

Faaker See, Faak:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 30 KBE/100ml
Temperature: 24°C

Ossiacher See, Annenheim:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 26.2°C

Wörthersee, Velden:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25°C

Silbersee, Villach:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.8°C

Rauschelesee, Nord:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 46 KBE/100ml
Temperature: 25.5°C

Weißensee, Stockenboi:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.7°C

Pressegger See, Nord:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.7°C

Millstätter See, Millstatt:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 30 KBE/100ml
Temperature: 25.1°C

Millstätter See, Döbriach:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.3°C

Millstätter See, Seeboden:
E.Coli: 46 KBE/100ml
Intestinal Enterococci: 61 KBE/100ml
Temperature: 24.8°C

Millstätter See, Süd:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.5°C

Weißensee, Techendorf Süd:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 77 KBE/100ml
Temperature: 23.2°C

Ossiacher See, Ossiach:
E.Coli: 30 KBE/100ml
Intestinal Enterococci: 30 KBE/100ml
Temperature: 24.7°C

Pressegger See, Nordost:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.9°C

Greifenburger Badesee, Nordwest:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.9°C

Ossiacher See, Bodensdorf:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.6°C

Längsee, St. Georgen:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.2°C

Klopeiner See, Unterburg:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24°C

Klopeiner See, St. Kanzian:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24°C

Turnersee, St. Primus:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25°C

Badesee Weihermühle, Gratwein:
E.Coli: 32 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25°C

Freizeitzentrum Copacabana, Kalsdorf:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.8°C

Badesee Kumberg:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 26.7°C

Schwarzl Freizeitzentrum, Unterpremstätten:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.8°C

Freizeitsee Aich:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 21 KBE/100ml
Temperature: 22.7°C

Putterersee, Aigen:
E.Coli: 21 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.7°C

Altausseersee West:
E.Coli: 21 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.3°C

Altausseersee Süd:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.7°C

Altausseersee Nord:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.4°C

Grundlsee Nord-West:
E.Coli: 21 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.6°C

Grundlsee Süd:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 146 KBE/100ml
Temperature: 21.3°C

Grundlsee Nord:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 53 KBE/100ml
Temperature: 22.9°C

Grundlsee Ost:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.4°C

Ödensee, Kainisch:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.1°C

Freizeitsee Au bei Turnau:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 16.5°C

Erlaufsee, St. Sebastian:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.3°C

Zenzsee, Tragöß:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 53 KBE/100ml
Temperature: 20.6°C

Leopoldsteiner See, Eisenerz:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 19.4°C

Badesee Steiner, Kraubath/Mur:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.1°C

Freizeitsee Wald/Schoberpass:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.1°C

Badesee Großsteinbach:
E.Coli: 21 KBE/100ml
Intestinal Enterococci: 21 KBE/100ml
Temperature: 26.1°C

Badesee Mönichwald:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 19.2°C

Stubenbergsee:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 26.5°C

Röcksee, Gosdorf:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.5°C

Stausee Soboth:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.7°C

Silbersee, Gralla:
E.Coli: 21 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.7°C

Sulmsee, Tillmitsch:
E.Coli: 32 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.7°C

Badesee Wildon, Wildon:
E.Coli: 32 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.5°C

Freizeitzentrum Piberstein, Maria Lankowitz:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.2°C

Furtnerteich, Mariahof:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22°C

Badesee Mühlen:
E.Coli: 21 KBE/100ml
Intestinal Enterococci: 21 KBE/100ml
Temperature: 22.9°C

Grasluppteich, Zeutschach:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23°C

Wildenau Badesee:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.3°C

Heratingersee, Ibm:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 43 KBE/100ml
Temperature: 24.6°C

Holzöstersee, Franking:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.5°C

Mining Badesee:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.8°C

Höllerersee, St. Pantaleon:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.2°C

Mühlheim Badesee:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.4°C

Pramet Badesee:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.1°C

Pichlingersee, Linz:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.2°C

Weikerlsee, Linz:
E.Coli: 21 KBE/100ml
Intestinal Enterococci: 487 KBE/100ml
Temperature: 16.9°C

Traun-Oedt Badesee:
E.Coli: 21 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.3°C

Feldkirchen-Badesee (N-O):
E.Coli: 53 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.4°C

Pleschingersee, Steyregg:
E.Coli: 32 KBE/100ml
Intestinal Enterococci: 53 KBE/100ml
Temperature: 24.7°C

Badesee Steyregg:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.4°C

Ausee Hohenlohe, Luftenberg:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.8°C

Mitterkirchen Badesee:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.6°C

Waldhausen Badesee:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 21 KBE/100ml
Temperature: 19.4°C

Klaffer Badesee:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22°C

Elisabethsee, Klaus:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.7°C

Gleinkersee, Spital a.P.:
E.Coli: 32 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.7°C

Traunsee, Altmünster:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.3°C

Hallstättersee, Untersee:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 32 KBE/100ml
Temperature: 22.2°C

Offensee, Ebensee:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.9°C

Traunsee, Rindbach:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 21 KBE/100ml
Temperature: 21°C

Traunsee, Gmunden:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 32 KBE/100ml
Temperature: 20.4°C

Hallstättersee, Kesselgraben:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.9°C

Hallstättersee, Hallstatt:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 21 KBE/100ml
Temperature: 21.9°C

Hallstättersee, Obertraun:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.5°C

Wolfgangsee, Appesbach:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 32 KBE/100ml
Temperature: 24.6°C

Traunsee, Traunkirchen:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.8°C

Attersee, Attersee:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21°C

Mondsee, Loibichl:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.1°C

Mondsee, Mondsee:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.8°C

Regau Badesee:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 32 KBE/100ml
Temperature: 19.3°C

Mondsee, St. Lorenz:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.2°C

Attersee, Litzlberg:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21°C

Attersee, Seewalchen:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.6°C

Attersee, Weißenbach:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.6°C

Attersee, Steinbach:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.7°C

Attersee, Unterach:
E.Coli: 21 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.8°C

Attersee, Weyregg:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.7°C

Irr- oder Zellersee, Laiter:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 21 KBE/100ml
Temperature: 22.2°C

Irr- oder Zellersee, Tiefgraben:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 43 KBE/100ml
Temperature: 22.5°C

Irr- oder Zellersee, Zell am Moos:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.6°C

Prebersee, Tamsweg:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.6°C

Badesee Gastein, Bad Hofgastein:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.4°C

Reitecksee, Flachau:
E.Coli: 30 KBE/100ml
Intestinal Enterococci: 61 KBE/100ml
Temperature: 22.3°C

Winklersee, Flachau:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 20.5°C

Böndlsee, Goldegg:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.9°C

Goldegger See:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.8°C

Badesee Hollersbach:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23°C

Badesee Niedernsill:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.3°C

Ritzensee, Saalfelden:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.8°C

Badesee Uttendorf:
E.Coli: 94 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24.3°C

Zeller See, Erlberg:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 30 KBE/100ml
Temperature: 22.2°C

Zeller See, Prielau:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 94 KBE/100ml
Temperature: 21.8°C

Zeller See, Schüttdorf:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.5°C

Zeller See, Thumersbach:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.3°C

Zeller See, Zell am See:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 22.2°C

Lieferinger Badesee, Salzburg:
E.Coli: 270 KBE/100ml
Intestinal Enterococci: 77 KBE/100ml
Temperature: 25.9°C

Bürgerausee, Kuchl:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.2°C

Seewaldsee, St. Koloman:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 21.4°C

Waldbad Anif:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 19.9°C

Grabensee, Perwang:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.9°C

Bürmooser See:
E.Coli: 46 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 24°C

Fuschlsee, Fuschl:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 23.2°C

Wallersee, Henndorf:
E.Coli: 15 KBE/100ml
Intestinal Enterococci: 15 KBE/100ml
Temperature: 25.5°C

Hintersee:
E.Coli: 15 KBE/100ml

In [3]:
df = pd.json_normalize(data)
df

,BADEGEWAESSERID,BADEGEWAESSERNAME,BEZIRK,GEMEINDE,LONGITUDE,LATITUDE,ANSPRECHSTELLE,STRASSE_NUMMER,PLZ_ORT,TELEFON,...,WASSERQUALITAET_JAHR_HEUER,QUALITAET_2026,WASSERQUALITAET_JAHR_VORIGES,QUALITAET_2025,WASSERQUALITAET_JAHR_VOR_VORIGES,QUALITAET_2024,WASSERQUALITAET_JAHR_VOR_VOR_VORIGES,QUALITAET_2023,QUALITAET_2022,MESSWERTE
0,AT1051051100150010,Naturbadesee Königsdorf,Jennersdorf,Königsdorf,16.1632530000,47.0082870000,Bezirkshauptmannschaft Jennersdorf,Hauptplatz 15,8380 - Jennersdorf,+43 3329 45202,...,,,,,A,A,A,A,G,"[{'D': '19.08.2025', 'O_E': None, 'E': 21, 'O_..."
1,AT1110002000120010,Sonnensee Ritzing,Oberpullendorf,Ritzing,16.470699,47.629901,Bezirkshauptmannschaft Oberpullendorf,Hauptstraße 56,7350 - Oberpullendorf,+43 2612 42531,...,,,,,A,A,A,A,A,"[{'D': '18.08.2025', 'O_E': '<N', 'E': 15, 'O_..."
2,AT1120000200060010,"Neusiedlersee, Rust",Rust(Stadt),Rust,16.700199,47.8026,Magistrat der Stadt Rust,Conradplatz 1,7071 - Rust,0,...,,,,,A,A,A,A,A,"[{'D': '25.08.2025', 'O_E': '<N', 'E': 15, 'O_..."
3,AT1120000300060010,"Neusiedlersee, Breitenbrunn",Eisenstadt-Umgebung,Breitenbrunn,16.766899,47.914798,Bezirkshauptmannschaft Eisenstadt-Umgebung,Ing. Julius Raab Straße 1,7000 - Eisenstadt,+43 2682 706,...,,,,,A,A,B,B,B,"[{'D': '25.08.2025', 'O_E': '<N', 'E': 15, 'O_..."
4,AT1120000900060010,"Neusiedlersee, Mörbisch",Eisenstadt-Umgebung,Mörbisch am See,16.6993,47.752799,Bezirkshauptmannschaft Eisenstadt-Umgebung,Ing. Julius Raab Straße 1,7000 - Eisenstadt,+43 2682 706,...,,,,,A,A,A,A,A,"[{'D': '25.08.2025', 'O_E': '<N', 'E': 15, 'O_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,AT3420002300060010,"Rheinauen, Hohenems",Dornbirn,Hohenems,9.654709,47.367698,Bezirkshauptmannschaft Dornbirn,Klaudiastraße 2,6850 - Dornbirn,+43 5572 3080,...,,,,,A,A,A,A,A,"[{'D': '25.08.2025', 'O_E': None, 'E': 110, 'O..."
256,AT3420002400010010,"Alter Rhein, Lustenau",Dornbirn,Lustenau,9.65954,47.399299,Bezirkshauptmannschaft Dornbirn,Klaudiastraße 2,6850 - Dornbirn,+43 5572 3080,...,,,,,A,A,A,A,A,"[{'D': '25.08.2025', 'O_E': '<N', 'E': 15, 'O_..."
257,AT3420002900080010,"Untere Au, Frastanz",Feldkirch,Frastanz,9.63467,47.2233,Bezirkshauptmannschaft Feldkirch,Schloßgraben 1,6800 - Feldkirch,+43 5522 35910,...,,,,,A,A,A,A,A,"[{'D': '25.08.2025', 'O_E': '<N', 'E': 15, 'O_..."
258,AT3420003800020010,"Baggersee Paspels, Rankweil",Feldkirch,Rankweil,9.58996,47.280399,Bezirkshauptmannschaft Feldkirch,Schloßgraben 1,6800 - Feldkirch,+43 5522 35910,...,,,,,A,A,A,A,A,"[{'D': '29.08.2025', 'O_E': None, 'E': 54, 'O_..."
259,AT3428021500030100,"Bodensee, FKK Hard",Bregenz,Hard,9.664060,47.495020,Bezirkshauptmannschaft Bregenz,Seestraße 1,6900 - Bregenz,+43 5574 8368230,...,,,,,A,A,A,A,A,"[{'D': '25.08.2025', 'O_E': None, 'E': 30, 'O_..."

In [4]:
locations = df[[
    "BADEGEWAESSERID", "BADEGEWAESSERNAME", "BEZIRK", "LATITUDE", "LONGITUDE"
]].rename(columns={
    "BADEGEWAESSERID": "id",
    "BADEGEWAESSERNAME": "name",
    "BEZIRK": "alternate_name",
    "LATITUDE": "lat",
    "LONGITUDE": "lon"
}).set_index("id")
locations['lat'], locations['lon'] = locations['lat'].astype(
    'float'), locations['lon'].astype('float')
locations

,name,alternate_name,lat,lon
id,,,,
AT1051051100150010,Naturbadesee Königsdorf,Jennersdorf,47.008287,16.163253
AT1110002000120010,Sonnensee Ritzing,Oberpullendorf,47.629901,16.470699
AT1120000200060010,"Neusiedlersee, Rust",Rust(Stadt),47.802600,16.700199
AT1120000300060010,"Neusiedlersee, Breitenbrunn",Eisenstadt-Umgebung,47.914798,16.766899
AT1120000900060010,"Neusiedlersee, Mörbisch",Eisenstadt-Umgebung,47.752799,16.699300
...,...,...,...,...
AT3420002300060010,"Rheinauen, Hohenems",Dornbirn,47.367698,9.654709
AT3420002400010010,"Alter Rhein, Lustenau",Dornbirn,47.399299,9.659540
AT3420002900080010,"Untere Au, Frastanz",Feldkirch,47.223300,9.634670
AT3420003800020010,"Baggersee Paspels, Rankweil",Feldkirch,47.280399,9.589960
AT3428021500030100,"Bodensee, FKK Hard",Bregenz,47.495020,9.664060

In [5]:
db = sqlite3.connect("../dataset.sqlite3")
locations.to_sql("locations", db, if_exists="append")

260