In [67]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO

In [68]:
url = "https://nnk.gov.hu/index.php/kozegeszsegugyi-laboratoriumi-foosztaly/terkepes-informaciok/furdovizminosegi-terkep"

In [69]:
headers = {
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
            "Cookie": ""
}
website = requests.get(url, headers=headers)
soup = BeautifulSoup(website.text, "html.parser")
table = soup.find_all("table")
table

[<table class="jelmagyarazat">
 <tbody>
 <tr>
 <td style="width: 20px; height: 20px; background-color: #0074ff;"> </td>
 <td style="width: 10px;"> </td>
 <td>Kiváló</td>
 </tr>
 <tr>
 <td style="width: 20px; height: 5px;"><span style="font-size: 8pt;"></span></td>
 <td style="width: 10px;"><span style="font-size: 8pt;"></span></td>
 <td><span style="font-size: 8pt;"></span></td>
 </tr>
 <tr>
 <td style="width: 20px; height: 20px; background-color: #74dfff;"> </td>
 <td> </td>
 <td>Jó</td>
 </tr>
 <tr>
 <td style="width: 20px; height: 5px;"><span style="font-size: 8pt;"></span></td>
 <td><span style="font-size: 8pt;"></span></td>
 <td><span style="font-size: 8pt;"></span></td>
 </tr>
 <tr>
 <td style="width: 20px; height: 20px; background-color: #55ff00;"> </td>
 <td> </td>
 <td>Tűrhető</td>
 </tr>
 <tr>
 <td style="width: 20px; height: 5px;"><span style="font-size: 8pt;"></span></td>
 <td><span style="font-size: 8pt;"></span></td>
 <td><span style="font-size: 8pt;"></span></td>
 </tr>
 <tr>
 <td style="width: 20px; height: 20px; background-color: #f00;"> </td>
 <td> </td>
 <td>Kifogásolt</td>
 </tr>
 <tr>
 <td style="width: 20px; height: 5px;"><span style="font-size: 8pt;"></span></td>
 <td><span style="font-size: 8pt;"></span></td>
 <td><span style="font-size: 8pt;"></span></td>
 </tr>
 <tr>
 <td style="width: 20px; height: 20px; background-color: #b3b3b3;"> </td>
 <td> </td>
 <td>Nem minősíthető</td>
 </tr>
 <tr>
 <td style="width: 20px; height: 5px;"><span style="font-size: 8pt;"></span></td>
 <td><span style="font-size: 8pt;"></span></td>
 <td><span style="font-size: 8pt;"></span></td>
 </tr>
 <tr>
 <td colspan="3" style="width: 20px; height: 20px; text-align: center;"><span style="color: #339966;">Jelmagyarázat</span></td>
 </tr>
 </tbody>
 </table>,

In [70]:
data = table[1]

In [71]:
df = pd.read_html(StringIO(data.prettify()))[0]

In [72]:
df2 = df.iloc[: , :-2]
df2

,"Szélesség, Hosszúság",Helyszín,Mérés dátuma,Cím,Vízminőség
0,"47.483255,20.587067","Abádszalók, Tisza-tó Strand",2025. 08. 11.,"Abádszalók, Tisza-tó Strand",kiváló
1,"46.811400,17.571700","Ábrahámhegy, Községi strand",2025. 08. 05.,"Ábrahámhegy, Községi strand",kiváló
2,"47.198440,18.601920","Agárd, Napsugár Strand",2025. 09. 01.,"Agárd, Napsugár Strand",jó
3,"47.193190,18.587830","Agárd, Park Strand Kemping",2025. 09. 01.,"Agárd, Park Strand Kemping",kiváló
4,"47.196049,18.596285","Agárd, VVSI Sport Hotel Strand",2025. 08. 11.,"Agárd, VVSI Sport Hotel Strand",jó
...,...,...,...,...,...
274,"46.882461,17.913806","Zamárdi, Mirabella Kemping",2025. 08. 12.,"Zamárdi, Mirabella Kemping",kiváló
275,"46.886921,17.940055","Zamárdi, Nagy szabadstrand (Kiss Ernő utca)",2025. 08. 12.,"Zamárdi, Nagy szabadstrand (Kiss Ernő utca)",kiváló
276,"46.872800,17.711700","Zánka, Erzsébet Tábor Strandfürdő",2025. 09. 08.,"Zánka, Erzsébet Tábor Strandfürdő",kiváló
277,"46.870090,17.686900","Zánka, Községi strand",2025. 08. 18.,"Zánka, Községi strand",kiváló
278,"47.798093,18.908666",Zebegényi Szabadstrand,2025. 08. 04.,Zebegényi Szabadstrand,jó

In [73]:
df2.rename(mapper={
    "Szélesség, Hosszúság": "coordinates",
    "Helyszín": "name",
    "Mérés dátuma": "measurement_date",
    "Cím": "address",
    "Vízminőség": "quality"
}, axis=1, inplace=True)

In [74]:
df2['lat'] = df2['coordinates'].apply(lambda x: x.split(',')[0])
df2['lon'] = df2['coordinates'].apply(lambda x: x.split(',')[1])

In [75]:
df2['id'] = range(1, len(df) + 1)

In [76]:
df2 = df2[[
    'id', 'name', 'lat', 'lon'
]]

In [77]:
df2

      id                                         name        lat        lon
0      1                  Abádszalók, Tisza-tó Strand  47.483255  20.587067
1      2                  Ábrahámhegy, Községi strand  46.811400  17.571700
2      3                       Agárd, Napsugár Strand  47.198440  18.601920
3      4                   Agárd, Park Strand Kemping  47.193190  18.587830
4      5               Agárd, VVSI Sport Hotel Strand  47.196049  18.596285
..   ...                                          ...        ...        ...
274  275                   Zamárdi, Mirabella Kemping  46.882461  17.913806
275  276  Zamárdi, Nagy szabadstrand (Kiss Ernő utca)  46.886921  17.940055
276  277            Zánka, Erzsébet Tábor Strandfürdő  46.872800  17.711700
277  278                        Zánka, Községi strand  46.870090  17.686900
278  279                       Zebegényi Szabadstrand  47.798093  18.908666

[279 rows x 4 columns]